/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CheapestListing } from "../CheapestListing.ts";

export type DiscoverCollectibleListSerializerResponse = {
    /**
     * @type integer
    */
    asset_id: number;
    /**
     * @minLength 1
     * @type string | undefined
    */
    readonly title?: string;
    /**
     * @type string | undefined
    */
    readonly primary_image?: string;
    /**
     * @type string, decimal
    */
    readonly rarity_score?: string | null;
    /**
     * @type object
    */
    cheapest_listing: CheapestListing;
};