/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type NotificationV2SerializerResponseTypeEnum = "transaction-sent" | "transaction-received" | "transaction-failed" | "asset-support-request" | "asset-support-success" | "asset-transaction-sent" | "asset-transaction-received" | "asset-transaction-failed" | "broadcast" | "rekey-address" | "None" | "tinyman-v1-1-swap" | "tinyman-v1-1-mint" | "tinyman-v1-1-burn" | "inbox-asset-transaction-received" | "inbox-asset-transaction-sent" | "inbox-asset-claimed" | "inbox-asset-rejected" | "custom-text-message" | "favorited-asset-price-change" | "algo-price-change" | "favorited-asset-is-top-mover" | "card-payment" | "card-refund" | "card-spend-incentive" | "card-withdraw" | "card-deposit";

export type NotificationV2SerializerResponse = {
    /**
     * @type integer | undefined
    */
    readonly id?: number;
    /**
     * @type integer
    */
    account?: number | null;
    /**
     * @type string | undefined
    */
    type?: NotificationV2SerializerResponseTypeEnum;
    /**
     * @type string | undefined
    */
    readonly message?: string;
    /**
     * @type string | undefined, date-time
    */
    readonly creation_datetime?: string;
    /**
     * @type object
    */
    metadata?: object | null;
    /**
     * @type string | undefined
    */
    readonly is_unread?: string;
};