/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod";

export const publicAssetVerificationDetailSerializerResponseSchema = z.object({
    "asset_id": z.number().int().min(0).max(9223372036854776000),
"verification_tier": z.enum(["verified", "unverified", "suspicious"]),
"explorer_url": z.string().url().min(1)
    })

export type PublicAssetVerificationDetailSerializerResponseSchema = z.infer<typeof publicAssetVerificationDetailSerializerResponseSchema>