name: 'Get Last Successful Run'
description: 'Finds the SHA of the last successful workflow run on the current branch'

inputs:
  workflow:
    description: 'The workflow file name (e.g., qa.yml or release.yml)'
    required: true
  event:
    description: 'Optional event type to filter by (e.g., schedule, workflow_dispatch)'
    required: false
    default: ''

outputs:
  sha:
    description: 'The commit SHA of the last successful run (empty if none found)'
    value: ${{ steps.find.outputs.sha }}
  has_changes:
    description: 'Whether there are changes since the last successful run'
    value: ${{ steps.find.outputs.has_changes }}

runs:
  using: 'composite'
  steps:
    - name: Find last successful run
      id: find
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        BRANCH="${GITHUB_REF_NAME}"
        WORKFLOW="${{ inputs.workflow }}"
        EVENT="${{ inputs.event }}"
        CURRENT_SHA="${GITHUB_SHA}"

        echo "Looking for last successful run of ${WORKFLOW} on branch ${BRANCH}..."
        if [ -n "$EVENT" ]; then
          echo "Filtering by event: ${EVENT}"
        fi

        # Build the gh run list command
        GH_ARGS=(
          --workflow="${WORKFLOW}"
          --branch="${BRANCH}"
          --status=success
          --limit=10
          --json headSha
          --jq '.[0].headSha // empty'
        )

        # Add event filter if specified
        if [ -n "$EVENT" ]; then
          GH_ARGS+=(--event="${EVENT}")
        fi

        LAST_SHA=$(gh run list "${GH_ARGS[@]}" 2>/dev/null || echo "")

        echo "Last successful run SHA: ${LAST_SHA:-none}"
        echo "Current SHA: $CURRENT_SHA"

        # Output the SHA (may be empty)
        echo "sha=$LAST_SHA" >> $GITHUB_OUTPUT

        # Determine if there are changes
        if [ -z "$LAST_SHA" ]; then
          echo "No previous successful run found - has changes"
          echo "has_changes=true" >> $GITHUB_OUTPUT
        elif [ "$LAST_SHA" = "$CURRENT_SHA" ]; then
          echo "No changes since last successful run"
          echo "has_changes=false" >> $GITHUB_OUTPUT
        else
          echo "Changes detected since last successful run"
          echo "has_changes=true" >> $GITHUB_OUTPUT
        fi
