# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, '16.0'
prepare_react_native_project!

# Map custom project configurations to Pods standard configurations
project 'pera.xcodeproj',
  'Dev' => :debug,
  'Staging' => :release,
  'Production' => :release


ENV['RCT_NEW_ARCH_ENABLED'] = '1'
linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'pera' do
  $VCEnableLocation = false
  config = use_native_modules!
  
  $RNFirebaseAsStaticFramework = true

  pod 'FirebaseInstallations', :modular_headers => true # Add missing package
  pod 'GoogleDataTransport', :modular_headers => true # Add missing package
  pod 'nanopb', :modular_headers => true # Add missing package
  pod 'GoogleUtilities', :modular_headers => true # Add missing package
  pod 'FirebaseCore', :modular_headers => true    # Add missing package
  pod 'FirebaseABTesting', :modular_headers => true # Add missing package
  pod 'FirebaseCoreExtension', :modular_headers => true # Add missing package
  pod 'FirebaseSessions', :modular_headers => true # Add missing package
  pod 'FirebaseAnalytics', :modular_headers => true # Add missing package
  pod 'FirebaseRemoteConfig', :modular_headers => true # Add missing package
  pod 'FirebaseMessaging', :modular_headers => true # Add missing package
  pod 'RNFBApp', :path => '../node_modules/@react-native-firebase/app' # Firebase manual setup


  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    # Fix for custom build configurations (Dev, Staging, Production)
    # CocoaPods only generates xcconfig files for Debug/Release configurations.
    # For custom configurations, we need to ensure all required build variables are set.
    # We force-set these values (not using ||=) because the xcconfig might set them to empty.
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |build_config|
        build_config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'

        # Force set all the required Pods build variables
        build_config.build_settings['PODS_ROOT'] = '${SRCROOT}'
        build_config.build_settings['PODS_BUILD_DIR'] = '${BUILD_DIR}'
        build_config.build_settings['PODS_CONFIGURATION_BUILD_DIR'] = '${PODS_BUILD_DIR}/$(CONFIGURATION)$(EFFECTIVE_PLATFORM_NAME)'
        build_config.build_settings['PODS_XCFRAMEWORKS_BUILD_DIR'] = '$(PODS_CONFIGURATION_BUILD_DIR)/XCFrameworkIntermediates'
      end
    end
  end
end
