/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type NFDomainLookupResponseSerializerResponse = {
    /**
     * @minLength 1
     * @type string
    */
    name: string;
    /**
     * @minLength 1
     * @type string
    */
    source: string;
    /**
     * @minLength 1
     * @type string
    */
    image: string;
};