/*
 Copyright 2022-2025 Pera Wallet, LDA
 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License
 */

import { queryClient, type Network } from '@perawallet/wallet-core-shared'
import type { PeraWebBackupResponse } from '../models'

/**
 * `GET /v1/backups/{id}/`
 *
 * Returns the encrypted backup row generated by Pera Web's "Transfer
 * Accounts" flow. The Django serializer name-spaces fields with snake_case
 * (`encrypted_content`, `creator_device`); we surface the raw shape and let
 * the decrypt step do the parsing.
 *
 * No Zod schema here because the only field we actually consume is
 * `encrypted_content`, and `decryptPeraWebBackupPayload` already validates
 * its presence and base64 shape. A schema would buy us nothing beyond a
 * second source of truth for the same field names.
 */
export const fetchPeraWebBackup = async (
    network: Network,
    backupId: string,
): Promise<PeraWebBackupResponse> => {
    const response = await queryClient<PeraWebBackupResponse>({
        backend: 'pera',
        network,
        method: 'GET',
        // `backupId` originates from a scanned QR, so encode it before
        // interpolating: a raw `../`, `?` or `#` would otherwise retarget the
        // request to a different backend path.
        url: `/v1/backups/${encodeURIComponent(backupId)}/`,
    })
    return response.data
}
