/*
 Copyright 2022-2025 Pera Wallet, LDA
 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License
 */

import type { Transaction } from './indexer-models'

//TODO for now we're stealing our data types from those autogenerated from the Indexer REST API - we probably want to use algokit's types 
// instead or something
export * from './indexer-models'

export const MAX_TX_NOTE_BYTES = 1024

export type SignRequest = {
    id?: string
    // A list of transaction groups (which in turn are a list of transactions)
    txs: Transaction[][]
}

export type BlockchainStore = {
    pendingSignRequests: SignRequest[]
    addSignRequest: (request: SignRequest) => boolean
    removeSignRequest: (request: SignRequest) => boolean
}