name: 'Generate Changelog'
description: 'Generates a changelog from conventional commits since the last successful build'

inputs:
  workflow:
    description: 'The workflow file name to check for last successful run (e.g., qa.yml)'
    required: true

outputs:
  changelog:
    description: 'The generated changelog formatted for Slack'
    value: ${{ steps.changelog.outputs.changelog }}

runs:
  using: 'composite'
  steps:
    - name: Get last successful run
      id: last_run
      uses: ./.github/actions/get-last-successful-run
      with:
        workflow: ${{ inputs.workflow }}

    - name: Generate Changelog
      id: changelog
      shell: bash
      run: |
        LAST_SHA="${{ steps.last_run.outputs.sha }}"

        if [ -n "$LAST_SHA" ] && git cat-file -t "$LAST_SHA" >/dev/null 2>&1; then
          echo "Found last successful build at commit: $LAST_SHA"
          LAST_REF="$LAST_SHA"
        else
          echo "No previous successful build found, using initial commit"
          LAST_REF=$(git rev-list --max-parents=0 HEAD)
        fi

        echo "Generating changelog from $LAST_REF to HEAD"

        # Generate changelog from conventional commits
        CHANGELOG=""

        # Features
        FEATURES=$(git log ${LAST_REF}..HEAD --pretty=format:"%s" --grep="^feat" | sed -E 's/^feat(\([^)]*\))?[:]? *//')
        if [ -n "$FEATURES" ]; then
          CHANGELOG="${CHANGELOG}*Features:*\n"
          while IFS= read -r line; do
            [ -n "$line" ] && CHANGELOG="${CHANGELOG}• ${line}\n"
          done <<< "$FEATURES"
          CHANGELOG="${CHANGELOG}\n"
        fi

        # Bug fixes
        FIXES=$(git log ${LAST_REF}..HEAD --pretty=format:"%s" --grep="^fix" | sed -E 's/^fix(\([^)]*\))?[:]? *//')
        if [ -n "$FIXES" ]; then
          CHANGELOG="${CHANGELOG}*Bug Fixes:*\n"
          while IFS= read -r line; do
            [ -n "$line" ] && CHANGELOG="${CHANGELOG}• ${line}\n"
          done <<< "$FIXES"
          CHANGELOG="${CHANGELOG}\n"
        fi

        # Other changes (chore, refactor, perf, test, docs, build)
        OTHER=$(git log ${LAST_REF}..HEAD --pretty=format:"%s" --grep="^\(chore\|refactor\|perf\|test\|docs\|build\)" | sed -E 's/^(chore|refactor|perf|test|docs|build)(\([^)]*\))?[:]? *//')
        if [ -n "$OTHER" ]; then
          CHANGELOG="${CHANGELOG}*Other:*\n"
          while IFS= read -r line; do
            [ -n "$line" ] && CHANGELOG="${CHANGELOG}• ${line}\n"
          done <<< "$OTHER"
        fi

        # If no conventional commits found, show recent commits
        if [ -z "$CHANGELOG" ]; then
          RECENT=$(git log ${LAST_REF}..HEAD --pretty=format:"• %s" --no-merges | head -10)
          if [ -n "$RECENT" ]; then
            CHANGELOG="*Recent commits:*\n${RECENT}"
          else
            CHANGELOG="No changes since last build"
          fi
        fi

        # Escape for GitHub Actions output
        CHANGELOG="${CHANGELOG//'%'/'%25'}"
        CHANGELOG="${CHANGELOG//$'\n'/'%0A'}"
        CHANGELOG="${CHANGELOG//$'\r'/'%0D'}"

        echo "changelog=$CHANGELOG" >> $GITHUB_OUTPUT
