name: 'Generate Changelog'
description: 'Generates a changelog from conventional commits since the last successful build'

inputs:
  workflow:
    description: 'The workflow file name to check for last successful run (e.g., qa.yml)'
    required: true

outputs:
  changelog:
    description: 'The generated changelog formatted for Slack'
    value: ${{ steps.changelog.outputs.changelog }}

runs:
  using: 'composite'
  steps:
    - name: Get last successful run
      id: last_run
      uses: ./.github/actions/get-last-successful-run
      with:
        workflow: ${{ inputs.workflow }}

    - name: Generate Changelog
      id: changelog
      shell: bash
      run: |
        LAST_SHA="${{ steps.last_run.outputs.sha }}"

        if [ -n "$LAST_SHA" ] && git cat-file -t "$LAST_SHA" >/dev/null 2>&1; then
          echo "Found last successful build at commit: $LAST_SHA"
          LAST_REF="$LAST_SHA"
        else
          echo "No previous successful build found, using initial commit"
          LAST_REF=$(git rev-list --max-parents=0 HEAD)
        fi

        echo "Generating changelog from $LAST_REF to HEAD"

        # Generate changelog from conventional commits
        CHANGELOG=""

        # Helper function to format sections
        format_section() {
          local title="$1"
          local content="$2"
          
          # Convert JIRA PERA-??? to Slack links
          local linked_content=$(echo "$content" | sed -E 's/(PERA-[0-9]+)/<https:\/\/algorandfoundation.atlassian.net\/browse\/\1|\1>/g')

          if [ -n "$linked_content" ]; then
            echo "$title"
            local count=$(echo "$content" | grep -c "^")
            if [ "$count" -gt 7 ]; then
              echo "$linked_content" | head -n 7 | while IFS= read -r line; do echo "• $line"; done
              local more=$((count - 7))
              echo "• ...and $more more"
            else
              echo "$linked_content" | while IFS= read -r line; do echo "• $line"; done
            fi
            echo ""
          fi
        }

        # Features
        FEATURES=$(git log ${LAST_REF}..HEAD --pretty=format:"%s" --grep="^feat" | sed -E 's/^feat(\([^)]*\))?[:]? *//')
        if [ -n "$FEATURES" ]; then
          SECTION=$(format_section "*Features:*" "$FEATURES")
          CHANGELOG="${CHANGELOG}${SECTION}"$'\n'
        fi

        # Bug fixes
        FIXES=$(git log ${LAST_REF}..HEAD --pretty=format:"%s" --grep="^fix" | sed -E 's/^fix(\([^)]*\))?[:]? *//')
        if [ -n "$FIXES" ]; then
          SECTION=$(format_section "*Bug Fixes:*" "$FIXES")
          CHANGELOG="${CHANGELOG}${SECTION}"$'\n'
        fi

        # Other changes (chore, refactor, perf, test, docs, build)
        OTHER=$(git log ${LAST_REF}..HEAD --pretty=format:"%s" --grep="^\(chore\|refactor\|perf\|test\|docs\|build\)" | sed -E 's/^(chore|refactor|perf|test|docs|build)(\([^)]*\))?[:]? *//')
        if [ -n "$OTHER" ]; then
          SECTION=$(format_section "*Other:*" "$OTHER")
          CHANGELOG="${CHANGELOG}${SECTION}"$'\n'
        fi

        # If no conventional commits found, show recent commits
        if [ -z "$CHANGELOG" ]; then
          RECENT=$(git log ${LAST_REF}..HEAD --pretty=format:"• %s" --no-merges | head -10)
          if [ -n "$RECENT" ]; then
            CHANGELOG="*Recent commits:*\n${RECENT}"
          else
            CHANGELOG="No changes since last build"
          fi
        fi

        # Escape for GitHub Actions output
        CHANGELOG="${CHANGELOG//'%'/'%25'}"
        CHANGELOG="${CHANGELOG//$'\n'/'%0A'}"
        CHANGELOG="${CHANGELOG//$'\r'/'%0D'}"

        echo "changelog=$CHANGELOG" >> $GITHUB_OUTPUT
