# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"
# Gems for Ruby 3.4+ compatibility
gem 'nkf'
gem 'mutex_m'
gem 'base64'
gem 'bigdecimal'
gem 'ostruct'

gem 'cocoapods', '~> 1.15.2'
gem 'fastlane'

# Load Fastlane plugins from Pluginfile
plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
