/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { discoverAssetSchema } from "../discoverAssetSchema.ts";
import { discoverSimpleNFTCollectionSchema } from "../discoverSimpleNFTCollectionSchema.ts";
import { mediaSchema } from "../mediaSchema.ts";
import { traitSchema } from "../traitSchema.ts";
import { z } from "zod";

export const discoverCollectibleDetailSerializerResponseSchema = z.object({
    "standards": z.string().optional(),
"primary_image": z.string().optional(),
"title": z.string().min(1).optional(),
"description": z.string().min(1).optional(),
"media": z.array(z.lazy(() => mediaSchema)),
"media_type": z.string().optional(),
"rarity_score": z.string().nullable().nullish(),
"rarity_rank": z.string().optional(),
"traits": z.array(z.lazy(() => traitSchema)),
"explorer_url": z.string().url().min(1),
"collection": z.lazy(() => discoverSimpleNFTCollectionSchema),
"asset": z.lazy(() => discoverAssetSchema)
    })

export type DiscoverCollectibleDetailSerializerResponseSchema = z.infer<typeof discoverCollectibleDetailSerializerResponseSchema>