/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { BackupRetrieveUpdateDestroySerializerRequest } from "./backupRetrieveUpdateDestroySerializer/Request.ts";
import type { BackupRetrieveUpdateDestroySerializerResponse } from "./backupRetrieveUpdateDestroySerializer/Response.ts";

export type V1BackupsUpdatePathParams = {
    /**
     * @description A UUID string identifying this backup.
     * @type string, uuid
    */
    id: string;
};

export type V1BackupsUpdateHeaderParams = {
    /**
     * @type string
    */
    "X-Modification-Key": string;
};

export type V1BackupsUpdate200 = BackupRetrieveUpdateDestroySerializerResponse;

export type V1BackupsUpdateMutationRequest = BackupRetrieveUpdateDestroySerializerRequest;

export type V1BackupsUpdateMutationResponse = V1BackupsUpdate200;

export type V1BackupsUpdateMutation = {
    Response: V1BackupsUpdate200;
    Request: V1BackupsUpdateMutationRequest;
    PathParams: V1BackupsUpdatePathParams;
    HeaderParams: V1BackupsUpdateHeaderParams;
    Errors: any;
};