/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DeviceAccountSerializerRequest } from "./deviceAccountSerializer/Request.ts";
import type { DeviceAccountSerializerResponse } from "./deviceAccountSerializer/Response.ts";

export type V1DevicesAccountsUpdatePathParams = {
    /**
     * @type string
    */
    address: string;
    /**
     * @type string
    */
    device_id: string;
};

export type V1DevicesAccountsUpdate200 = DeviceAccountSerializerResponse;

export type V1DevicesAccountsUpdateMutationRequest = DeviceAccountSerializerRequest;

export type V1DevicesAccountsUpdateMutationResponse = V1DevicesAccountsUpdate200;

export type V1DevicesAccountsUpdateMutation = {
    Response: V1DevicesAccountsUpdate200;
    Request: V1DevicesAccountsUpdateMutationRequest;
    PathParams: V1DevicesAccountsUpdatePathParams;
    Errors: any;
};