/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod";

export const discoverListingListSerializerResponseSchema = z.object({
    "id": z.number().int().optional(),
"provider": z.enum(["randgallery", "algoxnft", "shufl", "exa_market"]).optional(),
"amount_in_algo": z.string().describe("total amount paid to seller, provider and creator in microalgo").optional(),
"external_url": z.string().optional(),
"update_datetime": z.string().datetime().optional(),
"seller_address": z.string().min(1).optional()
    })

export type DiscoverListingListSerializerResponseSchema = z.infer<typeof discoverListingListSerializerResponseSchema>