/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod";

export const currencySerializerResponseSchema = z.object({
    "generated_at": z.string().optional(),
"currency_id": z.string().min(1).max(255),
"name": z.string().min(1).max(255),
"symbol": z.string().min(1).max(255)
    })

export type CurrencySerializerResponseSchema = z.infer<typeof currencySerializerResponseSchema>