/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod";

export const accountSchema = z.object({
    "id": z.number().int().optional(),
"address": z.string().min(1).max(255),
"is_verified_asset_creator": z.string().optional()
    })

export type AccountSchema = z.infer<typeof accountSchema>