/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod";

export const chainDynamicsSchema = z.object({
    "last_round": z.string().optional(),
"transaction_count": z.string().optional(),
"transactions_per_second": z.string().optional(),
"algo_price_change_percentage": z.string().optional(),
"algo_price_in_usd": z.string().optional(),
"market_cap_in_usd": z.string().optional(),
"algo_holders_count": z.string().optional(),
"algo_circulation_supply": z.string().optional(),
"online_staked_amount": z.string().optional(),
"online_accounts_count": z.string().optional()
    })

export type ChainDynamicsSchema = z.infer<typeof chainDynamicsSchema>