/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod";

export const DEXSwapAssetSchema = z.object({
    "asset_id": z.number().int().optional(),
"logo": z.string().url().optional(),
"name": z.string().min(1).optional(),
"unit_name": z.string().min(1).optional(),
"total": z.string().optional(),
"fraction_decimals": z.number().int().optional(),
"verification_tier": z.enum(["verified", "unverified", "suspicious"]),
"usd_value": z.string().nullable().nullish()
    })

export type DEXSwapAssetSchema = z.infer<typeof DEXSwapAssetSchema>