/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod";

export const discoverAssetSchema = z.object({
    "asset_id": z.number().int().optional(),
"total": z.string().optional(),
"creation_block_datetime": z.string().datetime().optional(),
"creator_account_address": z.string().min(1),
"freeze_address": z.string().min(1),
"clawback_address": z.string().min(1)
    })

export type DiscoverAssetSchema = z.infer<typeof discoverAssetSchema>