/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { backupRetrieveUpdateDestroySerializerRequestSchema } from "./backupRetrieveUpdateDestroySerializer/requestSchema.ts";
import { backupRetrieveUpdateDestroySerializerResponseSchema } from "./backupRetrieveUpdateDestroySerializer/responseSchema.ts";
import { z } from "zod";

export const v1BackupsUpdatePathParamsSchema = z.object({
    "id": z.string().uuid().describe("A UUID string identifying this backup.")
    })

export type V1BackupsUpdatePathParamsSchema = z.infer<typeof v1BackupsUpdatePathParamsSchema>

export const v1BackupsUpdateHeaderParamsSchema = z.object({
    "X-Modification-Key": z.string()
    })

export type V1BackupsUpdateHeaderParamsSchema = z.infer<typeof v1BackupsUpdateHeaderParamsSchema>

export const v1BackupsUpdate200Schema = z.lazy(() => backupRetrieveUpdateDestroySerializerResponseSchema)

export type V1BackupsUpdate200Schema = z.infer<typeof v1BackupsUpdate200Schema>

export const v1BackupsUpdateMutationRequestSchema = z.lazy(() => backupRetrieveUpdateDestroySerializerRequestSchema)

export type V1BackupsUpdateMutationRequestSchema = z.infer<typeof v1BackupsUpdateMutationRequestSchema>

export const v1BackupsUpdateMutationResponseSchema = z.lazy(() => v1BackupsUpdate200Schema)

export type V1BackupsUpdateMutationResponseSchema = z.infer<typeof v1BackupsUpdateMutationResponseSchema>