/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { immersveFundAddressUpdateSerializerRequestSchema } from "./immersveFundAddressUpdateSerializer/requestSchema.ts";
import { immersveFundAddressUpdateSerializerResponseSchema } from "./immersveFundAddressUpdateSerializer/responseSchema.ts";
import { z } from "zod";

export const v1CardsFundAddressPartialUpdatePathParamsSchema = z.object({
    "address": z.string().describe("A unique value identifying this immersve fund address.")
    })

export type V1CardsFundAddressPartialUpdatePathParamsSchema = z.infer<typeof v1CardsFundAddressPartialUpdatePathParamsSchema>

export const v1CardsFundAddressPartialUpdate200Schema = z.lazy(() => immersveFundAddressUpdateSerializerResponseSchema)

export type V1CardsFundAddressPartialUpdate200Schema = z.infer<typeof v1CardsFundAddressPartialUpdate200Schema>

export const v1CardsFundAddressPartialUpdateMutationRequestSchema = z.lazy(() => immersveFundAddressUpdateSerializerRequestSchema)

export type V1CardsFundAddressPartialUpdateMutationRequestSchema = z.infer<typeof v1CardsFundAddressPartialUpdateMutationRequestSchema>

export const v1CardsFundAddressPartialUpdateMutationResponseSchema = z.lazy(() => v1CardsFundAddressPartialUpdate200Schema)

export type V1CardsFundAddressPartialUpdateMutationResponseSchema = z.infer<typeof v1CardsFundAddressPartialUpdateMutationResponseSchema>