/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { deviceSerializerRequestSchema } from "./deviceSerializer/requestSchema.ts";
import { deviceSerializerResponseSchema } from "./deviceSerializer/responseSchema.ts";
import { z } from "zod";

export const v1DevicesUpdatePathParamsSchema = z.object({
    "device_id": z.string()
    })

export type V1DevicesUpdatePathParamsSchema = z.infer<typeof v1DevicesUpdatePathParamsSchema>

export const v1DevicesUpdate200Schema = z.lazy(() => deviceSerializerResponseSchema)

export type V1DevicesUpdate200Schema = z.infer<typeof v1DevicesUpdate200Schema>

export const v1DevicesUpdateMutationRequestSchema = z.lazy(() => deviceSerializerRequestSchema)

export type V1DevicesUpdateMutationRequestSchema = z.infer<typeof v1DevicesUpdateMutationRequestSchema>

export const v1DevicesUpdateMutationResponseSchema = z.lazy(() => v1DevicesUpdate200Schema)

export type V1DevicesUpdateMutationResponseSchema = z.infer<typeof v1DevicesUpdateMutationResponseSchema>