/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { updateDeviceLastSeenNotificationSerializerRequestSchema } from "./updateDeviceLastSeenNotificationSerializer/requestSchema.ts";
import { updateDeviceLastSeenNotificationSerializerResponseSchema } from "./updateDeviceLastSeenNotificationSerializer/responseSchema.ts";
import { z } from "zod";

export const v1DevicesUpdateLastSeenNotificationUpdatePathParamsSchema = z.object({
    "device_id": z.string()
    })

export type V1DevicesUpdateLastSeenNotificationUpdatePathParamsSchema = z.infer<typeof v1DevicesUpdateLastSeenNotificationUpdatePathParamsSchema>

export const v1DevicesUpdateLastSeenNotificationUpdate200Schema = z.lazy(() => updateDeviceLastSeenNotificationSerializerResponseSchema)

export type V1DevicesUpdateLastSeenNotificationUpdate200Schema = z.infer<typeof v1DevicesUpdateLastSeenNotificationUpdate200Schema>

export const v1DevicesUpdateLastSeenNotificationUpdateMutationRequestSchema = z.lazy(() => updateDeviceLastSeenNotificationSerializerRequestSchema)

export type V1DevicesUpdateLastSeenNotificationUpdateMutationRequestSchema = z.infer<typeof v1DevicesUpdateLastSeenNotificationUpdateMutationRequestSchema>

export const v1DevicesUpdateLastSeenNotificationUpdateMutationResponseSchema = z.lazy(() => v1DevicesUpdateLastSeenNotificationUpdate200Schema)

export type V1DevicesUpdateLastSeenNotificationUpdateMutationResponseSchema = z.infer<typeof v1DevicesUpdateLastSeenNotificationUpdateMutationResponseSchema>