/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { discoverFeaturedNFTCollectionSerializerResponseSchema } from "./discoverFeaturedNFTCollectionSerializer/responseSchema.ts";
import { z } from "zod";

export const v1DiscoverNftFeaturedCollectionsListQueryParamsSchema = z.object({
    "ordering": z.string().describe("Which field to use when ordering the results.").optional(),
"limit": z.coerce.number().int().describe("Number of results to return per page.").optional(),
"offset": z.coerce.number().int().describe("The initial index from which to return the results.").optional()
    }).optional()

export type V1DiscoverNftFeaturedCollectionsListQueryParamsSchema = z.infer<typeof v1DiscoverNftFeaturedCollectionsListQueryParamsSchema>

export const v1DiscoverNftFeaturedCollectionsList200Schema = z.object({
    "count": z.number().int(),
"next": z.string().url().nullable().nullish(),
"previous": z.string().url().nullable().nullish(),
"results": z.array(z.lazy(() => discoverFeaturedNFTCollectionSerializerResponseSchema))
    })

export type V1DiscoverNftFeaturedCollectionsList200Schema = z.infer<typeof v1DiscoverNftFeaturedCollectionsList200Schema>

export const v1DiscoverNftFeaturedCollectionsListQueryResponseSchema = z.lazy(() => v1DiscoverNftFeaturedCollectionsList200Schema)

export type V1DiscoverNftFeaturedCollectionsListQueryResponseSchema = z.infer<typeof v1DiscoverNftFeaturedCollectionsListQueryResponseSchema>