/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { assetSerializerResponseSchema } from "./assetSerializer/responseSchema.ts";
import { z } from "zod";

export const v1DiscoverAssetsList200Schema = z.array(z.lazy(() => assetSerializerResponseSchema))

export type V1DiscoverAssetsList200Schema = z.infer<typeof v1DiscoverAssetsList200Schema>

export const v1DiscoverAssetsListQueryResponseSchema = z.lazy(() => v1DiscoverAssetsList200Schema)

export type V1DiscoverAssetsListQueryResponseSchema = z.infer<typeof v1DiscoverAssetsListQueryResponseSchema>