/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { publicAssetSerializerResponseSchema } from "./publicAssetSerializer/responseSchema.ts";
import { z } from "zod";

export const v1PublicAssetsListQueryParamsSchema = z.object({
    "filter": z.string().describe("['is_verified', 'is_collectible']").optional(),
"ordering": z.string().describe("Which field to use when ordering the results.").optional(),
"cursor": z.string().describe("The pagination cursor value.").optional(),
"limit": z.coerce.number().int().describe("Number of results to return per page.").optional()
    }).optional()

export type V1PublicAssetsListQueryParamsSchema = z.infer<typeof v1PublicAssetsListQueryParamsSchema>

export const v1PublicAssetsList200Schema = z.object({
    "next": z.string().url().nullable().nullish(),
"previous": z.string().url().nullable().nullish(),
"results": z.array(z.lazy(() => publicAssetSerializerResponseSchema))
    })

export type V1PublicAssetsList200Schema = z.infer<typeof v1PublicAssetsList200Schema>

export const v1PublicAssetsListQueryResponseSchema = z.lazy(() => v1PublicAssetsList200Schema)

export type V1PublicAssetsListQueryResponseSchema = z.infer<typeof v1PublicAssetsListQueryResponseSchema>