/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { searchResultSerializerResponseSchema } from "./searchResultSerializer/responseSchema.ts";
import { z } from "zod";

export const v1SearchListQueryParamsSchema = z.object({
    "has_collectible": z.string().optional(),
"q": z.string().optional(),
"available_on_discover_mobile": z.string().optional(),
"ordering": z.string().describe("Which field to use when ordering the results.").optional(),
"cursor": z.string().describe("The pagination cursor value.").optional(),
"limit": z.coerce.number().int().describe("Number of results to return per page.").optional()
    }).optional()

export type V1SearchListQueryParamsSchema = z.infer<typeof v1SearchListQueryParamsSchema>

export const v1SearchList200Schema = z.object({
    "next": z.string().url().nullable().nullish(),
"previous": z.string().url().nullable().nullish(),
"results": z.array(z.lazy(() => searchResultSerializerResponseSchema))
    })

export type V1SearchList200Schema = z.infer<typeof v1SearchList200Schema>

export const v1SearchListQueryResponseSchema = z.lazy(() => v1SearchList200Schema)

export type V1SearchListQueryResponseSchema = z.infer<typeof v1SearchListQueryResponseSchema>