/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { wealthHistoryResponseSerializerResponseSchema } from "./wealthHistoryResponseSerializer/responseSchema.ts";
import { z } from "zod";

export const v2AccountsWealthListPathParamsSchema = z.object({
    "account_address": z.string()
    })

export type V2AccountsWealthListPathParamsSchema = z.infer<typeof v2AccountsWealthListPathParamsSchema>

export const v2AccountsWealthListQueryParamsSchema = z.object({
    "ordering": z.string().describe("Which field to use when ordering the results.").optional(),
"period": z.enum(["one-year", "one-month", "one-week", "one-day"]),
"currency": z.string().describe("^[A-Z]{3}$")
    })

export type V2AccountsWealthListQueryParamsSchema = z.infer<typeof v2AccountsWealthListQueryParamsSchema>

export const v2AccountsWealthList200Schema = z.array(z.lazy(() => wealthHistoryResponseSerializerResponseSchema))

export type V2AccountsWealthList200Schema = z.infer<typeof v2AccountsWealthList200Schema>

export const v2AccountsWealthListQueryResponseSchema = z.lazy(() => v2AccountsWealthList200Schema)

export type V2AccountsWealthListQueryResponseSchema = z.infer<typeof v2AccountsWealthListQueryResponseSchema>