/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { deviceV2MergeSerializerRequestSchema } from "./deviceV2MergeSerializer/requestSchema.ts";
import { deviceV2MergeSerializerResponseSchema } from "./deviceV2MergeSerializer/responseSchema.ts";
import { z } from "zod";

export const v2DevicesMergeCreateHeaderParamsSchema = z.object({
    "APP-VERSION": .describe("Change App Version").optional()
    }).optional()

export type V2DevicesMergeCreateHeaderParamsSchema = z.infer<typeof v2DevicesMergeCreateHeaderParamsSchema>

export const v2DevicesMergeCreate201Schema = z.lazy(() => deviceV2MergeSerializerResponseSchema)

export type V2DevicesMergeCreate201Schema = z.infer<typeof v2DevicesMergeCreate201Schema>

export const v2DevicesMergeCreateMutationRequestSchema = z.lazy(() => deviceV2MergeSerializerRequestSchema)

export type V2DevicesMergeCreateMutationRequestSchema = z.infer<typeof v2DevicesMergeCreateMutationRequestSchema>

export const v2DevicesMergeCreateMutationResponseSchema = z.lazy(() => v2DevicesMergeCreate201Schema)

export type V2DevicesMergeCreateMutationResponseSchema = z.infer<typeof v2DevicesMergeCreateMutationResponseSchema>