/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { querySerializerForPostRequestSchema } from "./querySerializerForPost/requestSchema.ts";
import { responseSerializerResponseSchema } from "./responseSerializer/responseSchema.ts";
import { z } from "zod";

export const v2WalletWealthCreate200Schema = z.lazy(() => responseSerializerResponseSchema)

export type V2WalletWealthCreate200Schema = z.infer<typeof v2WalletWealthCreate200Schema>

export const v2WalletWealthCreateMutationRequestSchema = z.lazy(() => querySerializerForPostRequestSchema)

export type V2WalletWealthCreateMutationRequestSchema = z.infer<typeof v2WalletWealthCreateMutationRequestSchema>

export const v2WalletWealthCreateMutationResponseSchema = z.lazy(() => v2WalletWealthCreate200Schema)

export type V2WalletWealthCreateMutationResponseSchema = z.infer<typeof v2WalletWealthCreateMutationResponseSchema>