/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod";

export const notificationV2SerializerResponseSchema = z.object({
    "id": z.number().int().optional(),
"account": z.number().int().nullable().nullish(),
"type": z.enum(["transaction-sent", "transaction-received", "transaction-failed", "asset-support-request", "asset-support-success", "asset-transaction-sent", "asset-transaction-received", "asset-transaction-failed", "broadcast", "rekey-address", "None", "tinyman-v1-1-swap", "tinyman-v1-1-mint", "tinyman-v1-1-burn", "inbox-asset-transaction-received", "inbox-asset-transaction-sent", "inbox-asset-claimed", "inbox-asset-rejected", "custom-text-message", "favorited-asset-price-change", "algo-price-change", "favorited-asset-is-top-mover", "card-payment", "card-refund", "card-spend-incentive", "card-withdraw", "card-deposit"]).optional(),
"message": z.string().optional(),
"creation_datetime": z.string().datetime().optional(),
"metadata": z.object({
    
    }).nullable().nullish(),
"is_unread": z.string().optional()
    })

export type NotificationV2SerializerResponseSchema = z.infer<typeof notificationV2SerializerResponseSchema>