/*
 Copyright 2022-2026 Pera Wallet, LDA
 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License
 */

import type { ImageSourcePropType } from 'react-native'
import type { Banner, BannerType } from '@perawallet/wallet-core-banners'
import cardBg from '@assets/images/banners/card-bg.png'
import genericBg from '@assets/images/banners/generic-bg.png'
import governanceBg from '@assets/images/banners/governance-bg.png'
import retailBg from '@assets/images/banners/retail-bg.png'
import stakingBg from '@assets/images/banners/staking-bg.png'

// Every banner type has its own bundled artwork — generated by rendering
// the corresponding iOS PDF asset (Resources/Assets/Banner/*.pdf) at 1x/2x/3x
// via `sips`, with retail being the one that ships native PNG.
const TYPE_DEFAULT_BACKGROUNDS: Record<BannerType, ImageSourcePropType> = {
    generic: genericBg as ImageSourcePropType,
    governance: governanceBg as ImageSourcePropType,
    staking: stakingBg as ImageSourcePropType,
    card: cardBg as ImageSourcePropType,
    retail: retailBg as ImageSourcePropType,
}

// Precedence: server-supplied URL → bundled type-default. There is always a
// background image — banners are never rendered against a plain color.
export const getBannerBackgroundSource = (
    banner: Banner,
): ImageSourcePropType => {
    if (banner.backgroundImageUrl) {
        return { uri: banner.backgroundImageUrl }
    }
    return TYPE_DEFAULT_BACKGROUNDS[banner.type]
}
