/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { V1DiscoverInfoBannersListQueryResponse, V1DiscoverInfoBannersListQueryParams } from "../types/V1DiscoverInfoBannersList.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { v1DiscoverInfoBannersListQueryResponseSchema } from "../zod/v1DiscoverInfoBannersListSchema.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const v1DiscoverInfoBannersListQueryKey = (params?: V1DiscoverInfoBannersListQueryParams) => [{ url: '/v1/discover/info-banners/' }, ...(params ? [params] : [])] as const

export type V1DiscoverInfoBannersListQueryKey = ReturnType<typeof v1DiscoverInfoBannersListQueryKey>

/**
 * {@link /v1/discover/info-banners/}
 */
export async function v1DiscoverInfoBannersList({ params }: { params?: V1DiscoverInfoBannersListQueryParams }, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<V1DiscoverInfoBannersListQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/v1/discover/info-banners/`, params, ... requestConfig })  
  return v1DiscoverInfoBannersListQueryResponseSchema.parse(res.data)
}

export function v1DiscoverInfoBannersListQueryOptions({ params }: { params?: V1DiscoverInfoBannersListQueryParams }, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = v1DiscoverInfoBannersListQueryKey(params)
  return queryOptions<V1DiscoverInfoBannersListQueryResponse, ResponseErrorConfig<Error>, V1DiscoverInfoBannersListQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return v1DiscoverInfoBannersList({ params }, config)
   },
  })
}

/**
 * {@link /v1/discover/info-banners/}
 */
export function useV1DiscoverInfoBannersList<TData = V1DiscoverInfoBannersListQueryResponse, TQueryData = V1DiscoverInfoBannersListQueryResponse, TQueryKey extends QueryKey = V1DiscoverInfoBannersListQueryKey>({ params }: { params?: V1DiscoverInfoBannersListQueryParams }, options: 
{
  query?: Partial<QueryObserverOptions<V1DiscoverInfoBannersListQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? v1DiscoverInfoBannersListQueryKey(params)

  const query = useQuery({
   ...v1DiscoverInfoBannersListQueryOptions({ params }, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}