/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { V1DiscoverAssetsTrendingListQueryResponse } from "../types/V1DiscoverAssetsTrendingList.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { InfiniteData, QueryKey, QueryClient, InfiniteQueryObserverOptions, UseInfiniteQueryResult } from "@tanstack/react-query";
import { v1DiscoverAssetsTrendingListQueryResponseSchema } from "../zod/v1DiscoverAssetsTrendingListSchema.ts";
import { infiniteQueryOptions, useInfiniteQuery } from "@tanstack/react-query";

export const v1DiscoverAssetsTrendingListInfiniteQueryKey = () => [{ url: '/v1/discover/assets/trending/' }] as const

export type V1DiscoverAssetsTrendingListInfiniteQueryKey = ReturnType<typeof v1DiscoverAssetsTrendingListInfiniteQueryKey>

/**
 * {@link /v1/discover/assets/trending/}
 */
export async function v1DiscoverAssetsTrendingListInfinite(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<V1DiscoverAssetsTrendingListQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/v1/discover/assets/trending/`, ... requestConfig })  
  return v1DiscoverAssetsTrendingListQueryResponseSchema.parse(res.data)
}

export function v1DiscoverAssetsTrendingListInfiniteQueryOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = v1DiscoverAssetsTrendingListInfiniteQueryKey()
  return infiniteQueryOptions<V1DiscoverAssetsTrendingListQueryResponse, ResponseErrorConfig<Error>, V1DiscoverAssetsTrendingListQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return v1DiscoverAssetsTrendingListInfinite(config)
   },
   initialPageParam: 0,
  getNextPageParam: (lastPage) => lastPage['nextPage'],
  getPreviousPageParam: (firstPage) => firstPage['nextPage']
  })
}

/**
 * {@link /v1/discover/assets/trending/}
 */
export function useV1DiscoverAssetsTrendingListInfinite<TData = InfiniteData<V1DiscoverAssetsTrendingListQueryResponse>, TQueryData = V1DiscoverAssetsTrendingListQueryResponse, TQueryKey extends QueryKey = V1DiscoverAssetsTrendingListInfiniteQueryKey>(options: 
{
  query?: Partial<InfiniteQueryObserverOptions<V1DiscoverAssetsTrendingListQueryResponse, ResponseErrorConfig<Error>, TQueryData, TQueryKey, TQueryData>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? v1DiscoverAssetsTrendingListInfiniteQueryKey()

  const query = useInfiniteQuery({
   ...v1DiscoverAssetsTrendingListInfiniteQueryOptions(config),
   queryKey,
   ...queryOptions
  } as unknown as InfiniteQueryObserverOptions, queryClient) as UseInfiniteQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}