/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { V1DiscoverNftCollectionsListQueryResponse, V1DiscoverNftCollectionsListQueryParams } from "../types/V1DiscoverNftCollectionsList.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { InfiniteData, QueryKey, QueryClient, InfiniteQueryObserverOptions, UseInfiniteQueryResult } from "@tanstack/react-query";
import { v1DiscoverNftCollectionsListQueryResponseSchema } from "../zod/v1DiscoverNftCollectionsListSchema.ts";
import { infiniteQueryOptions, useInfiniteQuery } from "@tanstack/react-query";

export const v1DiscoverNftCollectionsListInfiniteQueryKey = (params?: V1DiscoverNftCollectionsListQueryParams) => [{ url: '/v1/discover/nft/collections/' }, ...(params ? [params] : [])] as const

export type V1DiscoverNftCollectionsListInfiniteQueryKey = ReturnType<typeof v1DiscoverNftCollectionsListInfiniteQueryKey>

/**
 * {@link /v1/discover/nft/collections/}
 */
export async function v1DiscoverNftCollectionsListInfinite({ params }: { params?: V1DiscoverNftCollectionsListQueryParams }, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<V1DiscoverNftCollectionsListQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/v1/discover/nft/collections/`, params, ... requestConfig })  
  return v1DiscoverNftCollectionsListQueryResponseSchema.parse(res.data)
}

export function v1DiscoverNftCollectionsListInfiniteQueryOptions({ params }: { params?: V1DiscoverNftCollectionsListQueryParams }, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = v1DiscoverNftCollectionsListInfiniteQueryKey(params)
  return infiniteQueryOptions<V1DiscoverNftCollectionsListQueryResponse, ResponseErrorConfig<Error>, V1DiscoverNftCollectionsListQueryResponse, typeof queryKey, number>({
 
   queryKey,
   queryFn: async ({ signal, pageParam }) => {
      config.signal = signal
    
      if (!params) {
       params = { }
      }
      params['page'] = pageParam as unknown as V1DiscoverNftCollectionsListQueryParams['page']
      return v1DiscoverNftCollectionsListInfinite({ params }, config)
   },
   initialPageParam: 0,
  getNextPageParam: (lastPage) => lastPage['nextPage'],
  getPreviousPageParam: (firstPage) => firstPage['nextPage']
  })
}

/**
 * {@link /v1/discover/nft/collections/}
 */
export function useV1DiscoverNftCollectionsListInfinite<TData = InfiniteData<V1DiscoverNftCollectionsListQueryResponse>, TQueryData = V1DiscoverNftCollectionsListQueryResponse, TQueryKey extends QueryKey = V1DiscoverNftCollectionsListInfiniteQueryKey>({ params }: { params?: V1DiscoverNftCollectionsListQueryParams }, options: 
{
  query?: Partial<InfiniteQueryObserverOptions<V1DiscoverNftCollectionsListQueryResponse, ResponseErrorConfig<Error>, TQueryData, TQueryKey, TQueryData>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? v1DiscoverNftCollectionsListInfiniteQueryKey(params)

  const query = useInfiniteQuery({
   ...v1DiscoverNftCollectionsListInfiniteQueryOptions({ params }, config),
   queryKey,
   ...queryOptions
  } as unknown as InfiniteQueryObserverOptions, queryClient) as UseInfiniteQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}