/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { V1PublicLabeledAssetsListQueryResponse, V1PublicLabeledAssetsListQueryParams } from "../types/V1PublicLabeledAssetsList.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { v1PublicLabeledAssetsListQueryResponseSchema } from "../zod/v1PublicLabeledAssetsListSchema.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const v1PublicLabeledAssetsListSuspenseQueryKey = (params?: V1PublicLabeledAssetsListQueryParams) => [{ url: '/v1/public/labeled-assets/' }, ...(params ? [params] : [])] as const

export type V1PublicLabeledAssetsListSuspenseQueryKey = ReturnType<typeof v1PublicLabeledAssetsListSuspenseQueryKey>

/**
 * @description This is a simplified endpoint that returns all labeled assets in a single response. The endpoint returns verified and suspicious assets with asset verification label by excluding unverified ones. If your business logic needs to know the labeled asset ids, this is the endpoint you should use. It is lightweight and doesn't require pagination.- Response is cached for 5 min.
 * @summary Labeled Asset List
 * {@link /v1/public/labeled-assets/}
 */
export async function v1PublicLabeledAssetsListSuspense({ params }: { params?: V1PublicLabeledAssetsListQueryParams }, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<V1PublicLabeledAssetsListQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/v1/public/labeled-assets/`, params, ... requestConfig })  
  return v1PublicLabeledAssetsListQueryResponseSchema.parse(res.data)
}

export function v1PublicLabeledAssetsListSuspenseQueryOptions({ params }: { params?: V1PublicLabeledAssetsListQueryParams }, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = v1PublicLabeledAssetsListSuspenseQueryKey(params)
  return queryOptions<V1PublicLabeledAssetsListQueryResponse, ResponseErrorConfig<Error>, V1PublicLabeledAssetsListQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return v1PublicLabeledAssetsListSuspense({ params }, config)
   },
  })
}

/**
 * @description This is a simplified endpoint that returns all labeled assets in a single response. The endpoint returns verified and suspicious assets with asset verification label by excluding unverified ones. If your business logic needs to know the labeled asset ids, this is the endpoint you should use. It is lightweight and doesn't require pagination.- Response is cached for 5 min.
 * @summary Labeled Asset List
 * {@link /v1/public/labeled-assets/}
 */
export function useV1PublicLabeledAssetsListSuspense<TData = V1PublicLabeledAssetsListQueryResponse, TQueryKey extends QueryKey = V1PublicLabeledAssetsListSuspenseQueryKey>({ params }: { params?: V1PublicLabeledAssetsListQueryParams }, options: 
{
  query?: Partial<UseSuspenseQueryOptions<V1PublicLabeledAssetsListQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? v1PublicLabeledAssetsListSuspenseQueryKey(params)

  const query = useSuspenseQuery({
   ...v1PublicLabeledAssetsListSuspenseQueryOptions({ params }, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}