/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { V1DiscoverNftCollectiblesListingsListQueryResponse, V1DiscoverNftCollectiblesListingsListPathParams, V1DiscoverNftCollectiblesListingsListQueryParams } from "../types/V1DiscoverNftCollectiblesListingsList.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { InfiniteData, QueryKey, QueryClient, InfiniteQueryObserverOptions, UseInfiniteQueryResult } from "@tanstack/react-query";
import { v1DiscoverNftCollectiblesListingsListQueryResponseSchema } from "../zod/v1DiscoverNftCollectiblesListingsListSchema.ts";
import { infiniteQueryOptions, useInfiniteQuery } from "@tanstack/react-query";

export const v1DiscoverNftCollectiblesListingsListInfiniteQueryKey = ({ asset_id }: { asset_id: V1DiscoverNftCollectiblesListingsListPathParams["asset_id"] }, params?: V1DiscoverNftCollectiblesListingsListQueryParams) => [{ url: '/v1/discover/nft/collectibles/:asset_id/listings/', params: {asset_id:asset_id} }, ...(params ? [params] : [])] as const

export type V1DiscoverNftCollectiblesListingsListInfiniteQueryKey = ReturnType<typeof v1DiscoverNftCollectiblesListingsListInfiniteQueryKey>

/**
 * {@link /v1/discover/nft/collectibles/:asset_id/listings/}
 */
export async function v1DiscoverNftCollectiblesListingsListInfinite({ asset_id, params }: { asset_id: V1DiscoverNftCollectiblesListingsListPathParams["asset_id"]; params?: V1DiscoverNftCollectiblesListingsListQueryParams }, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<V1DiscoverNftCollectiblesListingsListQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/v1/discover/nft/collectibles/${asset_id}/listings/`, params, ... requestConfig })  
  return v1DiscoverNftCollectiblesListingsListQueryResponseSchema.parse(res.data)
}

export function v1DiscoverNftCollectiblesListingsListInfiniteQueryOptions({ asset_id, params }: { asset_id: V1DiscoverNftCollectiblesListingsListPathParams["asset_id"]; params?: V1DiscoverNftCollectiblesListingsListQueryParams }, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = v1DiscoverNftCollectiblesListingsListInfiniteQueryKey({ asset_id }, params)
  return infiniteQueryOptions<V1DiscoverNftCollectiblesListingsListQueryResponse, ResponseErrorConfig<Error>, V1DiscoverNftCollectiblesListingsListQueryResponse, typeof queryKey, number>({
   enabled: !!(asset_id),
   queryKey,
   queryFn: async ({ signal, pageParam }) => {
      config.signal = signal
    
      if (!params) {
       params = { }
      }
      params['page'] = pageParam as unknown as V1DiscoverNftCollectiblesListingsListQueryParams['page']
      return v1DiscoverNftCollectiblesListingsListInfinite({ asset_id, params }, config)
   },
   initialPageParam: 0,
  getNextPageParam: (lastPage) => lastPage['nextPage'],
  getPreviousPageParam: (firstPage) => firstPage['nextPage']
  })
}

/**
 * {@link /v1/discover/nft/collectibles/:asset_id/listings/}
 */
export function useV1DiscoverNftCollectiblesListingsListInfinite<TData = InfiniteData<V1DiscoverNftCollectiblesListingsListQueryResponse>, TQueryData = V1DiscoverNftCollectiblesListingsListQueryResponse, TQueryKey extends QueryKey = V1DiscoverNftCollectiblesListingsListInfiniteQueryKey>({ asset_id, params }: { asset_id: V1DiscoverNftCollectiblesListingsListPathParams["asset_id"]; params?: V1DiscoverNftCollectiblesListingsListQueryParams }, options: 
{
  query?: Partial<InfiniteQueryObserverOptions<V1DiscoverNftCollectiblesListingsListQueryResponse, ResponseErrorConfig<Error>, TQueryData, TQueryKey, TQueryData>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? v1DiscoverNftCollectiblesListingsListInfiniteQueryKey({ asset_id }, params)

  const query = useInfiniteQuery({
   ...v1DiscoverNftCollectiblesListingsListInfiniteQueryOptions({ asset_id, params }, config),
   queryKey,
   ...queryOptions
  } as unknown as InfiniteQueryObserverOptions, queryClient) as UseInfiniteQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}