/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { V1AccountsNamesBulkReadCreateMutationRequest, V1AccountsNamesBulkReadCreateMutationResponse } from "../types/V1AccountsNamesBulkReadCreate.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, QueryClient } from "@tanstack/react-query";
import { v1AccountsNamesBulkReadCreateMutationResponseSchema, v1AccountsNamesBulkReadCreateMutationRequestSchema } from "../zod/v1AccountsNamesBulkReadCreateSchema.ts";
import { useMutation } from "@tanstack/react-query";

export const v1AccountsNamesBulkReadCreateMutationKey = () => [{ url: '/v1/accounts/names/bulk-read/' }] as const

export type V1AccountsNamesBulkReadCreateMutationKey = ReturnType<typeof v1AccountsNamesBulkReadCreateMutationKey>

/**
 * @description For every account address that is provided in the request body, account names are returned (if any).
 * @summary Account Name Bulk Read
 * {@link /v1/accounts/names/bulk-read/}
 */
export async function v1AccountsNamesBulkReadCreate({ data }: { data: V1AccountsNamesBulkReadCreateMutationRequest }, config: Partial<RequestConfig<V1AccountsNamesBulkReadCreateMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = v1AccountsNamesBulkReadCreateMutationRequestSchema.parse(data)  
  
  const res = await request<V1AccountsNamesBulkReadCreateMutationResponse, ResponseErrorConfig<Error>, V1AccountsNamesBulkReadCreateMutationRequest>({ method : "POST", url : `/v1/accounts/names/bulk-read/`, data : requestData, ... requestConfig })  
  return v1AccountsNamesBulkReadCreateMutationResponseSchema.parse(res.data)
}

/**
 * @description For every account address that is provided in the request body, account names are returned (if any).
 * @summary Account Name Bulk Read
 * {@link /v1/accounts/names/bulk-read/}
 */
export function useV1AccountsNamesBulkReadCreate<TContext>(options: 
{
  mutation?: UseMutationOptions<V1AccountsNamesBulkReadCreateMutationResponse, ResponseErrorConfig<Error>, {data: V1AccountsNamesBulkReadCreateMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<V1AccountsNamesBulkReadCreateMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? v1AccountsNamesBulkReadCreateMutationKey()

  return useMutation<V1AccountsNamesBulkReadCreateMutationResponse, ResponseErrorConfig<Error>, {data: V1AccountsNamesBulkReadCreateMutationRequest}, TContext>({
    mutationFn: async({ data }) => {
      return v1AccountsNamesBulkReadCreate({ data }, config)
    },
    mutationKey,
    ...mutationOptions
  }, queryClient)
}