/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { V1AssetsReadQueryResponse, V1AssetsReadPathParams } from "../types/V1AssetsRead.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { v1AssetsReadQueryResponseSchema } from "../zod/v1AssetsReadSchema.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const v1AssetsReadQueryKey = ({ asset_id }: { asset_id: V1AssetsReadPathParams["asset_id"] }) => [{ url: '/v1/assets/:asset_id/', params: {asset_id:asset_id} }] as const

export type V1AssetsReadQueryKey = ReturnType<typeof v1AssetsReadQueryKey>

/**
 * @description This endpoint returns `Asset` information about a specific `ASA` on the Algorand blockchain.It also includes `Collectible` information when applicable. This is the recommended publicAPI for fetching the verification status of an `ASA` from Pera. More details about theverification program can be found here: https://explorer.perawallet.app/asa-verification/
 * @summary Asset Detail
 * {@link /v1/assets/:asset_id/}
 */
export async function v1AssetsRead({ asset_id }: { asset_id: V1AssetsReadPathParams["asset_id"] }, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<V1AssetsReadQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/v1/assets/${asset_id}/`, ... requestConfig })  
  return v1AssetsReadQueryResponseSchema.parse(res.data)
}

export function v1AssetsReadQueryOptions({ asset_id }: { asset_id: V1AssetsReadPathParams["asset_id"] }, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = v1AssetsReadQueryKey({ asset_id })
  return queryOptions<V1AssetsReadQueryResponse, ResponseErrorConfig<Error>, V1AssetsReadQueryResponse, typeof queryKey>({
   enabled: !!(asset_id),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return v1AssetsRead({ asset_id }, config)
   },
  })
}

/**
 * @description This endpoint returns `Asset` information about a specific `ASA` on the Algorand blockchain.It also includes `Collectible` information when applicable. This is the recommended publicAPI for fetching the verification status of an `ASA` from Pera. More details about theverification program can be found here: https://explorer.perawallet.app/asa-verification/
 * @summary Asset Detail
 * {@link /v1/assets/:asset_id/}
 */
export function useV1AssetsRead<TData = V1AssetsReadQueryResponse, TQueryData = V1AssetsReadQueryResponse, TQueryKey extends QueryKey = V1AssetsReadQueryKey>({ asset_id }: { asset_id: V1AssetsReadPathParams["asset_id"] }, options: 
{
  query?: Partial<QueryObserverOptions<V1AssetsReadQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? v1AssetsReadQueryKey({ asset_id })

  const query = useQuery({
   ...v1AssetsReadQueryOptions({ asset_id }, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}