/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { V1DevicesNotificationsListQueryResponse, V1DevicesNotificationsListPathParams, V1DevicesNotificationsListQueryParams } from "../types/V1DevicesNotificationsList.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { InfiniteData, QueryKey, QueryClient, InfiniteQueryObserverOptions, UseInfiniteQueryResult } from "@tanstack/react-query";
import { v1DevicesNotificationsListQueryResponseSchema } from "../zod/v1DevicesNotificationsListSchema.ts";
import { infiniteQueryOptions, useInfiniteQuery } from "@tanstack/react-query";

export const v1DevicesNotificationsListInfiniteQueryKey = ({ device_id }: { device_id: V1DevicesNotificationsListPathParams["device_id"] }, params?: V1DevicesNotificationsListQueryParams) => [{ url: '/v1/devices/:device_id/notifications/', params: {device_id:device_id} }, ...(params ? [params] : [])] as const

export type V1DevicesNotificationsListInfiniteQueryKey = ReturnType<typeof v1DevicesNotificationsListInfiniteQueryKey>

/**
 * {@link /v1/devices/:device_id/notifications/}
 */
export async function v1DevicesNotificationsListInfinite({ device_id, params }: { device_id: V1DevicesNotificationsListPathParams["device_id"]; params?: V1DevicesNotificationsListQueryParams }, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<V1DevicesNotificationsListQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/v1/devices/${device_id}/notifications/`, params, ... requestConfig })  
  return v1DevicesNotificationsListQueryResponseSchema.parse(res.data)
}

export function v1DevicesNotificationsListInfiniteQueryOptions({ device_id, params }: { device_id: V1DevicesNotificationsListPathParams["device_id"]; params?: V1DevicesNotificationsListQueryParams }, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = v1DevicesNotificationsListInfiniteQueryKey({ device_id }, params)
  return infiniteQueryOptions<V1DevicesNotificationsListQueryResponse, ResponseErrorConfig<Error>, V1DevicesNotificationsListQueryResponse, typeof queryKey, number>({
   enabled: !!(device_id),
   queryKey,
   queryFn: async ({ signal, pageParam }) => {
      config.signal = signal
    
      if (!params) {
       params = { }
      }
      params['page'] = pageParam as unknown as V1DevicesNotificationsListQueryParams['page']
      return v1DevicesNotificationsListInfinite({ device_id, params }, config)
   },
   initialPageParam: 0,
  getNextPageParam: (lastPage) => lastPage['nextPage'],
  getPreviousPageParam: (firstPage) => firstPage['nextPage']
  })
}

/**
 * {@link /v1/devices/:device_id/notifications/}
 */
export function useV1DevicesNotificationsListInfinite<TData = InfiniteData<V1DevicesNotificationsListQueryResponse>, TQueryData = V1DevicesNotificationsListQueryResponse, TQueryKey extends QueryKey = V1DevicesNotificationsListInfiniteQueryKey>({ device_id, params }: { device_id: V1DevicesNotificationsListPathParams["device_id"]; params?: V1DevicesNotificationsListQueryParams }, options: 
{
  query?: Partial<InfiniteQueryObserverOptions<V1DevicesNotificationsListQueryResponse, ResponseErrorConfig<Error>, TQueryData, TQueryKey, TQueryData>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? v1DevicesNotificationsListInfiniteQueryKey({ device_id }, params)

  const query = useInfiniteQuery({
   ...v1DevicesNotificationsListInfiniteQueryOptions({ device_id, params }, config),
   queryKey,
   ...queryOptions
  } as unknown as InfiniteQueryObserverOptions, queryClient) as UseInfiniteQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}