/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { V1CardsCountryAvailabilityRequestCreateMutationRequest, V1CardsCountryAvailabilityRequestCreateMutationResponse, V1CardsCountryAvailabilityRequestCreate400 } from "../types/V1CardsCountryAvailabilityRequestCreate.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, QueryClient } from "@tanstack/react-query";
import { v1CardsCountryAvailabilityRequestCreateMutationResponseSchema, v1CardsCountryAvailabilityRequestCreateMutationRequestSchema } from "../zod/v1CardsCountryAvailabilityRequestCreateSchema.ts";
import { useMutation } from "@tanstack/react-query";

export const v1CardsCountryAvailabilityRequestCreateMutationKey = () => [{ url: '/v1/cards/country-availability-request/' }] as const

export type V1CardsCountryAvailabilityRequestCreateMutationKey = ReturnType<typeof v1CardsCountryAvailabilityRequestCreateMutationKey>

/**
 * @description Creates a new country availability request (waitlist entry).Either 'device' or 'address' must be provided, and 'alpha_2_country_code' is always required.
 * {@link /v1/cards/country-availability-request/}
 */
export async function v1CardsCountryAvailabilityRequestCreate({ data }: { data: V1CardsCountryAvailabilityRequestCreateMutationRequest }, config: Partial<RequestConfig<V1CardsCountryAvailabilityRequestCreateMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = v1CardsCountryAvailabilityRequestCreateMutationRequestSchema.parse(data)  
  
  const res = await request<V1CardsCountryAvailabilityRequestCreateMutationResponse, ResponseErrorConfig<V1CardsCountryAvailabilityRequestCreate400>, V1CardsCountryAvailabilityRequestCreateMutationRequest>({ method : "POST", url : `/v1/cards/country-availability-request/`, data : requestData, ... requestConfig })  
  return v1CardsCountryAvailabilityRequestCreateMutationResponseSchema.parse(res.data)
}

/**
 * @description Creates a new country availability request (waitlist entry).Either 'device' or 'address' must be provided, and 'alpha_2_country_code' is always required.
 * {@link /v1/cards/country-availability-request/}
 */
export function useV1CardsCountryAvailabilityRequestCreate<TContext>(options: 
{
  mutation?: UseMutationOptions<V1CardsCountryAvailabilityRequestCreateMutationResponse, ResponseErrorConfig<V1CardsCountryAvailabilityRequestCreate400>, {data: V1CardsCountryAvailabilityRequestCreateMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<V1CardsCountryAvailabilityRequestCreateMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? v1CardsCountryAvailabilityRequestCreateMutationKey()

  return useMutation<V1CardsCountryAvailabilityRequestCreateMutationResponse, ResponseErrorConfig<V1CardsCountryAvailabilityRequestCreate400>, {data: V1CardsCountryAvailabilityRequestCreateMutationRequest}, TContext>({
    mutationFn: async({ data }) => {
      return v1CardsCountryAvailabilityRequestCreate({ data }, config)
    },
    mutationKey,
    ...mutationOptions
  }, queryClient)
}