/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { V1WalletWealthListQueryResponse, V1WalletWealthListQueryParams } from "../types/V1WalletWealthList.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { InfiniteData, QueryKey, QueryClient, InfiniteQueryObserverOptions, UseInfiniteQueryResult } from "@tanstack/react-query";
import { v1WalletWealthListQueryResponseSchema } from "../zod/v1WalletWealthListSchema.ts";
import { infiniteQueryOptions, useInfiniteQuery } from "@tanstack/react-query";

export const v1WalletWealthListInfiniteQueryKey = (params: V1WalletWealthListQueryParams) => [{ url: '/v1/wallet/wealth/' }, ...(params ? [params] : [])] as const

export type V1WalletWealthListInfiniteQueryKey = ReturnType<typeof v1WalletWealthListInfiniteQueryKey>

/**
 * {@link /v1/wallet/wealth/}
 */
export async function v1WalletWealthListInfinite({ params }: { params: V1WalletWealthListQueryParams }, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<V1WalletWealthListQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/v1/wallet/wealth/`, params, ... requestConfig })  
  return v1WalletWealthListQueryResponseSchema.parse(res.data)
}

export function v1WalletWealthListInfiniteQueryOptions({ params }: { params: V1WalletWealthListQueryParams }, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = v1WalletWealthListInfiniteQueryKey(params)
  return infiniteQueryOptions<V1WalletWealthListQueryResponse, ResponseErrorConfig<Error>, V1WalletWealthListQueryResponse, typeof queryKey, number>({
   enabled: !!(params),
   queryKey,
   queryFn: async ({ signal, pageParam }) => {
      config.signal = signal
    
      if (!params) {
       params = { }
      }
      params['page'] = pageParam as unknown as V1WalletWealthListQueryParams['page']
      return v1WalletWealthListInfinite({ params }, config)
   },
   initialPageParam: 0,
  getNextPageParam: (lastPage) => lastPage['nextPage'],
  getPreviousPageParam: (firstPage) => firstPage['nextPage']
  })
}

/**
 * {@link /v1/wallet/wealth/}
 */
export function useV1WalletWealthListInfinite<TData = InfiniteData<V1WalletWealthListQueryResponse>, TQueryData = V1WalletWealthListQueryResponse, TQueryKey extends QueryKey = V1WalletWealthListInfiniteQueryKey>({ params }: { params: V1WalletWealthListQueryParams }, options: 
{
  query?: Partial<InfiniteQueryObserverOptions<V1WalletWealthListQueryResponse, ResponseErrorConfig<Error>, TQueryData, TQueryKey, TQueryData>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? v1WalletWealthListInfiniteQueryKey(params)

  const query = useInfiniteQuery({
   ...v1WalletWealthListInfiniteQueryOptions({ params }, config),
   queryKey,
   ...queryOptions
  } as unknown as InfiniteQueryObserverOptions, queryClient) as UseInfiniteQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}