/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { V1ProjectsCategoriesListQueryResponse, V1ProjectsCategoriesListQueryParams } from "../types/V1ProjectsCategoriesList.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { v1ProjectsCategoriesListQueryResponseSchema } from "../zod/v1ProjectsCategoriesListSchema.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const v1ProjectsCategoriesListQueryKey = (params?: V1ProjectsCategoriesListQueryParams) => [{ url: '/v1/projects/categories/' }, ...(params ? [params] : [])] as const

export type V1ProjectsCategoriesListQueryKey = ReturnType<typeof v1ProjectsCategoriesListQueryKey>

/**
 * {@link /v1/projects/categories/}
 * @deprecated
 */
export async function v1ProjectsCategoriesList({ params }: { params?: V1ProjectsCategoriesListQueryParams }, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<V1ProjectsCategoriesListQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/v1/projects/categories/`, params, ... requestConfig })  
  return v1ProjectsCategoriesListQueryResponseSchema.parse(res.data)
}

export function v1ProjectsCategoriesListQueryOptions({ params }: { params?: V1ProjectsCategoriesListQueryParams }, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = v1ProjectsCategoriesListQueryKey(params)
  return queryOptions<V1ProjectsCategoriesListQueryResponse, ResponseErrorConfig<Error>, V1ProjectsCategoriesListQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return v1ProjectsCategoriesList({ params }, config)
   },
  })
}

/**
 * {@link /v1/projects/categories/}
 * @deprecated
 */
export function useV1ProjectsCategoriesList<TData = V1ProjectsCategoriesListQueryResponse, TQueryData = V1ProjectsCategoriesListQueryResponse, TQueryKey extends QueryKey = V1ProjectsCategoriesListQueryKey>({ params }: { params?: V1ProjectsCategoriesListQueryParams }, options: 
{
  query?: Partial<QueryObserverOptions<V1ProjectsCategoriesListQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? v1ProjectsCategoriesListQueryKey(params)

  const query = useQuery({
   ...v1ProjectsCategoriesListQueryOptions({ params }, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}