/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { V1DiscoverPopularProjectsListQueryResponse, V1DiscoverPopularProjectsListQueryParams } from "../types/V1DiscoverPopularProjectsList.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { InfiniteData, QueryKey, QueryClient, InfiniteQueryObserverOptions, UseInfiniteQueryResult } from "@tanstack/react-query";
import { v1DiscoverPopularProjectsListQueryResponseSchema } from "../zod/v1DiscoverPopularProjectsListSchema.ts";
import { infiniteQueryOptions, useInfiniteQuery } from "@tanstack/react-query";

export const v1DiscoverPopularProjectsListInfiniteQueryKey = (params?: V1DiscoverPopularProjectsListQueryParams) => [{ url: '/v1/discover/popular-projects/' }, ...(params ? [params] : [])] as const

export type V1DiscoverPopularProjectsListInfiniteQueryKey = ReturnType<typeof v1DiscoverPopularProjectsListInfiniteQueryKey>

/**
 * {@link /v1/discover/popular-projects/}
 */
export async function v1DiscoverPopularProjectsListInfinite({ params }: { params?: V1DiscoverPopularProjectsListQueryParams }, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<V1DiscoverPopularProjectsListQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/v1/discover/popular-projects/`, params, ... requestConfig })  
  return v1DiscoverPopularProjectsListQueryResponseSchema.parse(res.data)
}

export function v1DiscoverPopularProjectsListInfiniteQueryOptions({ params }: { params?: V1DiscoverPopularProjectsListQueryParams }, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = v1DiscoverPopularProjectsListInfiniteQueryKey(params)
  return infiniteQueryOptions<V1DiscoverPopularProjectsListQueryResponse, ResponseErrorConfig<Error>, V1DiscoverPopularProjectsListQueryResponse, typeof queryKey, number>({
 
   queryKey,
   queryFn: async ({ signal, pageParam }) => {
      config.signal = signal
    
      if (!params) {
       params = { }
      }
      params['page'] = pageParam as unknown as V1DiscoverPopularProjectsListQueryParams['page']
      return v1DiscoverPopularProjectsListInfinite({ params }, config)
   },
   initialPageParam: 0,
  getNextPageParam: (lastPage) => lastPage['nextPage'],
  getPreviousPageParam: (firstPage) => firstPage['nextPage']
  })
}

/**
 * {@link /v1/discover/popular-projects/}
 */
export function useV1DiscoverPopularProjectsListInfinite<TData = InfiniteData<V1DiscoverPopularProjectsListQueryResponse>, TQueryData = V1DiscoverPopularProjectsListQueryResponse, TQueryKey extends QueryKey = V1DiscoverPopularProjectsListInfiniteQueryKey>({ params }: { params?: V1DiscoverPopularProjectsListQueryParams }, options: 
{
  query?: Partial<InfiniteQueryObserverOptions<V1DiscoverPopularProjectsListQueryResponse, ResponseErrorConfig<Error>, TQueryData, TQueryKey, TQueryData>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? v1DiscoverPopularProjectsListInfiniteQueryKey(params)

  const query = useInfiniteQuery({
   ...v1DiscoverPopularProjectsListInfiniteQueryOptions({ params }, config),
   queryKey,
   ...queryOptions
  } as unknown as InfiniteQueryObserverOptions, queryClient) as UseInfiniteQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}