/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { V1ExplorerChainDynamicsListQueryResponse, V1ExplorerChainDynamicsListQueryParams } from "../types/V1ExplorerChainDynamicsList.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { v1ExplorerChainDynamicsListQueryResponseSchema } from "../zod/v1ExplorerChainDynamicsListSchema.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const v1ExplorerChainDynamicsListQueryKey = (params?: V1ExplorerChainDynamicsListQueryParams) => [{ url: '/v1/explorer/chain-dynamics/' }, ...(params ? [params] : [])] as const

export type V1ExplorerChainDynamicsListQueryKey = ReturnType<typeof v1ExplorerChainDynamicsListQueryKey>

/**
 * @description Returns algo price, market cap, transaction count, tps, last round
 * @summary Chain Dynamics View
 * {@link /v1/explorer/chain-dynamics/}
 */
export async function v1ExplorerChainDynamicsList({ params }: { params?: V1ExplorerChainDynamicsListQueryParams }, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<V1ExplorerChainDynamicsListQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/v1/explorer/chain-dynamics/`, params, ... requestConfig })  
  return v1ExplorerChainDynamicsListQueryResponseSchema.parse(res.data)
}

export function v1ExplorerChainDynamicsListQueryOptions({ params }: { params?: V1ExplorerChainDynamicsListQueryParams }, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = v1ExplorerChainDynamicsListQueryKey(params)
  return queryOptions<V1ExplorerChainDynamicsListQueryResponse, ResponseErrorConfig<Error>, V1ExplorerChainDynamicsListQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return v1ExplorerChainDynamicsList({ params }, config)
   },
  })
}

/**
 * @description Returns algo price, market cap, transaction count, tps, last round
 * @summary Chain Dynamics View
 * {@link /v1/explorer/chain-dynamics/}
 */
export function useV1ExplorerChainDynamicsList<TData = V1ExplorerChainDynamicsListQueryResponse, TQueryData = V1ExplorerChainDynamicsListQueryResponse, TQueryKey extends QueryKey = V1ExplorerChainDynamicsListQueryKey>({ params }: { params?: V1ExplorerChainDynamicsListQueryParams }, options: 
{
  query?: Partial<QueryObserverOptions<V1ExplorerChainDynamicsListQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? v1ExplorerChainDynamicsListQueryKey(params)

  const query = useQuery({
   ...v1ExplorerChainDynamicsListQueryOptions({ params }, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}