/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { V1DiscoverAssetsPoolsListQueryResponse, V1DiscoverAssetsPoolsListPathParams } from "../types/V1DiscoverAssetsPoolsList.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { InfiniteData, QueryKey, QueryClient, InfiniteQueryObserverOptions, UseInfiniteQueryResult } from "@tanstack/react-query";
import { v1DiscoverAssetsPoolsListQueryResponseSchema } from "../zod/v1DiscoverAssetsPoolsListSchema.ts";
import { infiniteQueryOptions, useInfiniteQuery } from "@tanstack/react-query";

export const v1DiscoverAssetsPoolsListInfiniteQueryKey = ({ asset_id }: { asset_id: V1DiscoverAssetsPoolsListPathParams["asset_id"] }) => [{ url: '/v1/discover/assets/:asset_id/pools/', params: {asset_id:asset_id} }] as const

export type V1DiscoverAssetsPoolsListInfiniteQueryKey = ReturnType<typeof v1DiscoverAssetsPoolsListInfiniteQueryKey>

/**
 * @description Provides all pools of the asset.
 * {@link /v1/discover/assets/:asset_id/pools/}
 */
export async function v1DiscoverAssetsPoolsListInfinite({ asset_id }: { asset_id: V1DiscoverAssetsPoolsListPathParams["asset_id"] }, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<V1DiscoverAssetsPoolsListQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/v1/discover/assets/${asset_id}/pools/`, ... requestConfig })  
  return v1DiscoverAssetsPoolsListQueryResponseSchema.parse(res.data)
}

export function v1DiscoverAssetsPoolsListInfiniteQueryOptions({ asset_id }: { asset_id: V1DiscoverAssetsPoolsListPathParams["asset_id"] }, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = v1DiscoverAssetsPoolsListInfiniteQueryKey({ asset_id })
  return infiniteQueryOptions<V1DiscoverAssetsPoolsListQueryResponse, ResponseErrorConfig<Error>, V1DiscoverAssetsPoolsListQueryResponse, typeof queryKey>({
   enabled: !!(asset_id),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return v1DiscoverAssetsPoolsListInfinite({ asset_id }, config)
   },
   initialPageParam: 0,
  getNextPageParam: (lastPage) => lastPage['nextPage'],
  getPreviousPageParam: (firstPage) => firstPage['nextPage']
  })
}

/**
 * @description Provides all pools of the asset.
 * {@link /v1/discover/assets/:asset_id/pools/}
 */
export function useV1DiscoverAssetsPoolsListInfinite<TData = InfiniteData<V1DiscoverAssetsPoolsListQueryResponse>, TQueryData = V1DiscoverAssetsPoolsListQueryResponse, TQueryKey extends QueryKey = V1DiscoverAssetsPoolsListInfiniteQueryKey>({ asset_id }: { asset_id: V1DiscoverAssetsPoolsListPathParams["asset_id"] }, options: 
{
  query?: Partial<InfiniteQueryObserverOptions<V1DiscoverAssetsPoolsListQueryResponse, ResponseErrorConfig<Error>, TQueryData, TQueryKey, TQueryData>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? v1DiscoverAssetsPoolsListInfiniteQueryKey({ asset_id })

  const query = useInfiniteQuery({
   ...v1DiscoverAssetsPoolsListInfiniteQueryOptions({ asset_id }, config),
   queryKey,
   ...queryOptions
  } as unknown as InfiniteQueryObserverOptions, queryClient) as UseInfiniteQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}