/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { V1DevicesCreateMutationRequest, V1DevicesCreateMutationResponse } from "../types/V1DevicesCreate.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, QueryClient } from "@tanstack/react-query";
import { v1DevicesCreateMutationResponseSchema, v1DevicesCreateMutationRequestSchema } from "../zod/v1DevicesCreateSchema.ts";
import { useMutation } from "@tanstack/react-query";

export const v1DevicesCreateMutationKey = () => [{ url: '/v1/devices/' }] as const

export type V1DevicesCreateMutationKey = ReturnType<typeof v1DevicesCreateMutationKey>

/**
 * @description `push_token` needs to be sent to delete the device.
 * @summary Create & Delete Device View
 * {@link /v1/devices/}
 */
export async function v1DevicesCreate({ data }: { data: V1DevicesCreateMutationRequest }, config: Partial<RequestConfig<V1DevicesCreateMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = v1DevicesCreateMutationRequestSchema.parse(data)  
  
  const res = await request<V1DevicesCreateMutationResponse, ResponseErrorConfig<Error>, V1DevicesCreateMutationRequest>({ method : "POST", url : `/v1/devices/`, data : requestData, ... requestConfig })  
  return v1DevicesCreateMutationResponseSchema.parse(res.data)
}

/**
 * @description `push_token` needs to be sent to delete the device.
 * @summary Create & Delete Device View
 * {@link /v1/devices/}
 */
export function useV1DevicesCreate<TContext>(options: 
{
  mutation?: UseMutationOptions<V1DevicesCreateMutationResponse, ResponseErrorConfig<Error>, {data: V1DevicesCreateMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<V1DevicesCreateMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? v1DevicesCreateMutationKey()

  return useMutation<V1DevicesCreateMutationResponse, ResponseErrorConfig<Error>, {data: V1DevicesCreateMutationRequest}, TContext>({
    mutationFn: async({ data }) => {
      return v1DevicesCreate({ data }, config)
    },
    mutationKey,
    ...mutationOptions
  }, queryClient)
}