/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { V1AccountsNamesListQueryResponse, V1AccountsNamesListPathParams, V1AccountsNamesListQueryParams } from "../types/V1AccountsNamesList.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { InfiniteData, QueryKey, QueryClient, InfiniteQueryObserverOptions, UseInfiniteQueryResult } from "@tanstack/react-query";
import { v1AccountsNamesListQueryResponseSchema } from "../zod/v1AccountsNamesListSchema.ts";
import { infiniteQueryOptions, useInfiniteQuery } from "@tanstack/react-query";

export const v1AccountsNamesListInfiniteQueryKey = ({ account_address }: { account_address: V1AccountsNamesListPathParams["account_address"] }, params?: V1AccountsNamesListQueryParams) => [{ url: '/v1/accounts/:account_address/names/', params: {account_address:account_address} }, ...(params ? [params] : [])] as const

export type V1AccountsNamesListInfiniteQueryKey = ReturnType<typeof v1AccountsNamesListInfiniteQueryKey>

/**
 * @description Returns a list of names of an account.
 * @summary Account Names View
 * {@link /v1/accounts/:account_address/names/}
 */
export async function v1AccountsNamesListInfinite({ account_address, params }: { account_address: V1AccountsNamesListPathParams["account_address"]; params?: V1AccountsNamesListQueryParams }, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<V1AccountsNamesListQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/v1/accounts/${account_address}/names/`, params, ... requestConfig })  
  return v1AccountsNamesListQueryResponseSchema.parse(res.data)
}

export function v1AccountsNamesListInfiniteQueryOptions({ account_address, params }: { account_address: V1AccountsNamesListPathParams["account_address"]; params?: V1AccountsNamesListQueryParams }, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = v1AccountsNamesListInfiniteQueryKey({ account_address }, params)
  return infiniteQueryOptions<V1AccountsNamesListQueryResponse, ResponseErrorConfig<Error>, V1AccountsNamesListQueryResponse, typeof queryKey, number>({
   enabled: !!(account_address),
   queryKey,
   queryFn: async ({ signal, pageParam }) => {
      config.signal = signal
    
      if (!params) {
       params = { }
      }
      params['page'] = pageParam as unknown as V1AccountsNamesListQueryParams['page']
      return v1AccountsNamesListInfinite({ account_address, params }, config)
   },
   initialPageParam: 0,
  getNextPageParam: (lastPage) => lastPage['nextPage'],
  getPreviousPageParam: (firstPage) => firstPage['nextPage']
  })
}

/**
 * @description Returns a list of names of an account.
 * @summary Account Names View
 * {@link /v1/accounts/:account_address/names/}
 */
export function useV1AccountsNamesListInfinite<TData = InfiniteData<V1AccountsNamesListQueryResponse>, TQueryData = V1AccountsNamesListQueryResponse, TQueryKey extends QueryKey = V1AccountsNamesListInfiniteQueryKey>({ account_address, params }: { account_address: V1AccountsNamesListPathParams["account_address"]; params?: V1AccountsNamesListQueryParams }, options: 
{
  query?: Partial<InfiniteQueryObserverOptions<V1AccountsNamesListQueryResponse, ResponseErrorConfig<Error>, TQueryData, TQueryKey, TQueryData>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? v1AccountsNamesListInfiniteQueryKey({ account_address }, params)

  const query = useInfiniteQuery({
   ...v1AccountsNamesListInfiniteQueryOptions({ account_address, params }, config),
   queryKey,
   ...queryOptions
  } as unknown as InfiniteQueryObserverOptions, queryClient) as UseInfiniteQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}