/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { V1DiscoverNewsReadQueryResponse, V1DiscoverNewsReadPathParams } from "../types/V1DiscoverNewsRead.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { InfiniteData, QueryKey, QueryClient, InfiniteQueryObserverOptions, UseInfiniteQueryResult } from "@tanstack/react-query";
import { v1DiscoverNewsReadQueryResponseSchema } from "../zod/v1DiscoverNewsReadSchema.ts";
import { infiniteQueryOptions, useInfiniteQuery } from "@tanstack/react-query";

export const v1DiscoverNewsReadInfiniteQueryKey = ({ id }: { id: V1DiscoverNewsReadPathParams["id"] }) => [{ url: '/v1/discover/news/:id/', params: {id:id} }] as const

export type V1DiscoverNewsReadInfiniteQueryKey = ReturnType<typeof v1DiscoverNewsReadInfiniteQueryKey>

/**
 * {@link /v1/discover/news/:id/}
 */
export async function v1DiscoverNewsReadInfinite({ id }: { id: V1DiscoverNewsReadPathParams["id"] }, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<V1DiscoverNewsReadQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/v1/discover/news/${id}/`, ... requestConfig })  
  return v1DiscoverNewsReadQueryResponseSchema.parse(res.data)
}

export function v1DiscoverNewsReadInfiniteQueryOptions({ id }: { id: V1DiscoverNewsReadPathParams["id"] }, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = v1DiscoverNewsReadInfiniteQueryKey({ id })
  return infiniteQueryOptions<V1DiscoverNewsReadQueryResponse, ResponseErrorConfig<Error>, V1DiscoverNewsReadQueryResponse, typeof queryKey>({
   enabled: !!(id),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return v1DiscoverNewsReadInfinite({ id }, config)
   },
   initialPageParam: 0,
  getNextPageParam: (lastPage) => lastPage['nextPage'],
  getPreviousPageParam: (firstPage) => firstPage['nextPage']
  })
}

/**
 * {@link /v1/discover/news/:id/}
 */
export function useV1DiscoverNewsReadInfinite<TData = InfiniteData<V1DiscoverNewsReadQueryResponse>, TQueryData = V1DiscoverNewsReadQueryResponse, TQueryKey extends QueryKey = V1DiscoverNewsReadInfiniteQueryKey>({ id }: { id: V1DiscoverNewsReadPathParams["id"] }, options: 
{
  query?: Partial<InfiniteQueryObserverOptions<V1DiscoverNewsReadQueryResponse, ResponseErrorConfig<Error>, TQueryData, TQueryKey, TQueryData>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? v1DiscoverNewsReadInfiniteQueryKey({ id })

  const query = useInfiniteQuery({
   ...v1DiscoverNewsReadInfiniteQueryOptions({ id }, config),
   queryKey,
   ...queryOptions
  } as unknown as InfiniteQueryObserverOptions, queryClient) as UseInfiniteQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}