/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { V1ProjectsListQueryResponse, V1ProjectsListQueryParams } from "../types/V1ProjectsList.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { v1ProjectsListQueryResponseSchema } from "../zod/v1ProjectsListSchema.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const v1ProjectsListQueryKey = (params?: V1ProjectsListQueryParams) => [{ url: '/v1/projects/' }, ...(params ? [params] : [])] as const

export type V1ProjectsListQueryKey = ReturnType<typeof v1ProjectsListQueryKey>

/**
 * {@link /v1/projects/}
 */
export async function v1ProjectsList({ params }: { params?: V1ProjectsListQueryParams }, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<V1ProjectsListQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/v1/projects/`, params, ... requestConfig })  
  return v1ProjectsListQueryResponseSchema.parse(res.data)
}

export function v1ProjectsListQueryOptions({ params }: { params?: V1ProjectsListQueryParams }, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = v1ProjectsListQueryKey(params)
  return queryOptions<V1ProjectsListQueryResponse, ResponseErrorConfig<Error>, V1ProjectsListQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return v1ProjectsList({ params }, config)
   },
  })
}

/**
 * {@link /v1/projects/}
 */
export function useV1ProjectsList<TData = V1ProjectsListQueryResponse, TQueryData = V1ProjectsListQueryResponse, TQueryKey extends QueryKey = V1ProjectsListQueryKey>({ params }: { params?: V1ProjectsListQueryParams }, options: 
{
  query?: Partial<QueryObserverOptions<V1ProjectsListQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? v1ProjectsListQueryKey(params)

  const query = useQuery({
   ...v1ProjectsListQueryOptions({ params }, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}