/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { V1CardsFundAddressUpdateMutationRequest, V1CardsFundAddressUpdateMutationResponse, V1CardsFundAddressUpdatePathParams } from "../types/V1CardsFundAddressUpdate.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, QueryClient } from "@tanstack/react-query";
import { v1CardsFundAddressUpdateMutationResponseSchema, v1CardsFundAddressUpdateMutationRequestSchema } from "../zod/v1CardsFundAddressUpdateSchema.ts";
import { useMutation } from "@tanstack/react-query";

export const v1CardsFundAddressUpdateMutationKey = () => [{ url: '/v1/cards/fund-address/:address/' }] as const

export type V1CardsFundAddressUpdateMutationKey = ReturnType<typeof v1CardsFundAddressUpdateMutationKey>

/**
 * {@link /v1/cards/fund-address/:address/}
 */
export async function v1CardsFundAddressUpdate({ address, data }: { address: V1CardsFundAddressUpdatePathParams["address"]; data: V1CardsFundAddressUpdateMutationRequest }, config: Partial<RequestConfig<V1CardsFundAddressUpdateMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = v1CardsFundAddressUpdateMutationRequestSchema.parse(data)  
  
  const res = await request<V1CardsFundAddressUpdateMutationResponse, ResponseErrorConfig<Error>, V1CardsFundAddressUpdateMutationRequest>({ method : "PUT", url : `/v1/cards/fund-address/${address}/`, data : requestData, ... requestConfig })  
  return v1CardsFundAddressUpdateMutationResponseSchema.parse(res.data)
}

/**
 * {@link /v1/cards/fund-address/:address/}
 */
export function useV1CardsFundAddressUpdate<TContext>(options: 
{
  mutation?: UseMutationOptions<V1CardsFundAddressUpdateMutationResponse, ResponseErrorConfig<Error>, {address: V1CardsFundAddressUpdatePathParams["address"], data: V1CardsFundAddressUpdateMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<V1CardsFundAddressUpdateMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? v1CardsFundAddressUpdateMutationKey()

  return useMutation<V1CardsFundAddressUpdateMutationResponse, ResponseErrorConfig<Error>, {address: V1CardsFundAddressUpdatePathParams["address"], data: V1CardsFundAddressUpdateMutationRequest}, TContext>({
    mutationFn: async({ address, data }) => {
      return v1CardsFundAddressUpdate({ address, data }, config)
    },
    mutationKey,
    ...mutationOptions
  }, queryClient)
}