/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { V1CollectibleSalesGraphListQueryResponse, V1CollectibleSalesGraphListPathParams, V1CollectibleSalesGraphListQueryParams } from "../types/V1CollectibleSalesGraphList.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { v1CollectibleSalesGraphListQueryResponseSchema } from "../zod/v1CollectibleSalesGraphListSchema.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const v1CollectibleSalesGraphListQueryKey = ({ asset_id }: { asset_id: V1CollectibleSalesGraphListPathParams["asset_id"] }, params: V1CollectibleSalesGraphListQueryParams) => [{ url: '/v1/collectible/:asset_id/sales/graph/', params: {asset_id:asset_id} }, ...(params ? [params] : [])] as const

export type V1CollectibleSalesGraphListQueryKey = ReturnType<typeof v1CollectibleSalesGraphListQueryKey>

/**
 * @description Returns collectible sales history graph over a period
 * @summary Collectible Sales Graph
 * {@link /v1/collectible/:asset_id/sales/graph/}
 */
export async function v1CollectibleSalesGraphList({ asset_id, params }: { asset_id: V1CollectibleSalesGraphListPathParams["asset_id"]; params: V1CollectibleSalesGraphListQueryParams }, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<V1CollectibleSalesGraphListQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/v1/collectible/${asset_id}/sales/graph/`, params, ... requestConfig })  
  return v1CollectibleSalesGraphListQueryResponseSchema.parse(res.data)
}

export function v1CollectibleSalesGraphListQueryOptions({ asset_id, params }: { asset_id: V1CollectibleSalesGraphListPathParams["asset_id"]; params: V1CollectibleSalesGraphListQueryParams }, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = v1CollectibleSalesGraphListQueryKey({ asset_id }, params)
  return queryOptions<V1CollectibleSalesGraphListQueryResponse, ResponseErrorConfig<Error>, V1CollectibleSalesGraphListQueryResponse, typeof queryKey>({
   enabled: !!(asset_id&& params),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return v1CollectibleSalesGraphList({ asset_id, params }, config)
   },
  })
}

/**
 * @description Returns collectible sales history graph over a period
 * @summary Collectible Sales Graph
 * {@link /v1/collectible/:asset_id/sales/graph/}
 */
export function useV1CollectibleSalesGraphList<TData = V1CollectibleSalesGraphListQueryResponse, TQueryData = V1CollectibleSalesGraphListQueryResponse, TQueryKey extends QueryKey = V1CollectibleSalesGraphListQueryKey>({ asset_id, params }: { asset_id: V1CollectibleSalesGraphListPathParams["asset_id"]; params: V1CollectibleSalesGraphListQueryParams }, options: 
{
  query?: Partial<QueryObserverOptions<V1CollectibleSalesGraphListQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? v1CollectibleSalesGraphListQueryKey({ asset_id }, params)

  const query = useQuery({
   ...v1CollectibleSalesGraphListQueryOptions({ asset_id, params }, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}