/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { V1DiscoverNftFeaturedCollectionsListQueryResponse, V1DiscoverNftFeaturedCollectionsListQueryParams } from "../types/V1DiscoverNftFeaturedCollectionsList.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { InfiniteData, QueryKey, QueryClient, InfiniteQueryObserverOptions, UseInfiniteQueryResult } from "@tanstack/react-query";
import { v1DiscoverNftFeaturedCollectionsListQueryResponseSchema } from "../zod/v1DiscoverNftFeaturedCollectionsListSchema.ts";
import { infiniteQueryOptions, useInfiniteQuery } from "@tanstack/react-query";

export const v1DiscoverNftFeaturedCollectionsListInfiniteQueryKey = (params?: V1DiscoverNftFeaturedCollectionsListQueryParams) => [{ url: '/v1/discover/nft/featured-collections/' }, ...(params ? [params] : [])] as const

export type V1DiscoverNftFeaturedCollectionsListInfiniteQueryKey = ReturnType<typeof v1DiscoverNftFeaturedCollectionsListInfiniteQueryKey>

/**
 * {@link /v1/discover/nft/featured-collections/}
 */
export async function v1DiscoverNftFeaturedCollectionsListInfinite({ params }: { params?: V1DiscoverNftFeaturedCollectionsListQueryParams }, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<V1DiscoverNftFeaturedCollectionsListQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/v1/discover/nft/featured-collections/`, params, ... requestConfig })  
  return v1DiscoverNftFeaturedCollectionsListQueryResponseSchema.parse(res.data)
}

export function v1DiscoverNftFeaturedCollectionsListInfiniteQueryOptions({ params }: { params?: V1DiscoverNftFeaturedCollectionsListQueryParams }, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = v1DiscoverNftFeaturedCollectionsListInfiniteQueryKey(params)
  return infiniteQueryOptions<V1DiscoverNftFeaturedCollectionsListQueryResponse, ResponseErrorConfig<Error>, V1DiscoverNftFeaturedCollectionsListQueryResponse, typeof queryKey, number>({
 
   queryKey,
   queryFn: async ({ signal, pageParam }) => {
      config.signal = signal
    
      if (!params) {
       params = { }
      }
      params['page'] = pageParam as unknown as V1DiscoverNftFeaturedCollectionsListQueryParams['page']
      return v1DiscoverNftFeaturedCollectionsListInfinite({ params }, config)
   },
   initialPageParam: 0,
  getNextPageParam: (lastPage) => lastPage['nextPage'],
  getPreviousPageParam: (firstPage) => firstPage['nextPage']
  })
}

/**
 * {@link /v1/discover/nft/featured-collections/}
 */
export function useV1DiscoverNftFeaturedCollectionsListInfinite<TData = InfiniteData<V1DiscoverNftFeaturedCollectionsListQueryResponse>, TQueryData = V1DiscoverNftFeaturedCollectionsListQueryResponse, TQueryKey extends QueryKey = V1DiscoverNftFeaturedCollectionsListInfiniteQueryKey>({ params }: { params?: V1DiscoverNftFeaturedCollectionsListQueryParams }, options: 
{
  query?: Partial<InfiniteQueryObserverOptions<V1DiscoverNftFeaturedCollectionsListQueryResponse, ResponseErrorConfig<Error>, TQueryData, TQueryKey, TQueryData>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? v1DiscoverNftFeaturedCollectionsListInfiniteQueryKey(params)

  const query = useInfiniteQuery({
   ...v1DiscoverNftFeaturedCollectionsListInfiniteQueryOptions({ params }, config),
   queryKey,
   ...queryOptions
  } as unknown as InfiniteQueryObserverOptions, queryClient) as UseInfiniteQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}