/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { V2DevicesMeReadQueryResponse } from "../types/V2DevicesMeRead.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { v2DevicesMeReadQueryResponseSchema } from "../zod/v2DevicesMeReadSchema.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const v2DevicesMeReadQueryKey = () => [{ url: '/v2/devices/me/' }] as const

export type V2DevicesMeReadQueryKey = ReturnType<typeof v2DevicesMeReadQueryKey>

/**
 * {@link /v2/devices/me/}
 */
export async function v2DevicesMeRead(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<V2DevicesMeReadQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/v2/devices/me/`, ... requestConfig })  
  return v2DevicesMeReadQueryResponseSchema.parse(res.data)
}

export function v2DevicesMeReadQueryOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = v2DevicesMeReadQueryKey()
  return queryOptions<V2DevicesMeReadQueryResponse, ResponseErrorConfig<Error>, V2DevicesMeReadQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return v2DevicesMeRead(config)
   },
  })
}

/**
 * {@link /v2/devices/me/}
 */
export function useV2DevicesMeRead<TData = V2DevicesMeReadQueryResponse, TQueryData = V2DevicesMeReadQueryResponse, TQueryKey extends QueryKey = V2DevicesMeReadQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<V2DevicesMeReadQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? v2DevicesMeReadQueryKey()

  const query = useQuery({
   ...v2DevicesMeReadQueryOptions(config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}