/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { V2AccountsWealthListQueryResponse, V2AccountsWealthListPathParams, V2AccountsWealthListQueryParams } from "../types/V2AccountsWealthList.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { InfiniteData, QueryKey, QueryClient, InfiniteQueryObserverOptions, UseInfiniteQueryResult } from "@tanstack/react-query";
import { v2AccountsWealthListQueryResponseSchema } from "../zod/v2AccountsWealthListSchema.ts";
import { infiniteQueryOptions, useInfiniteQuery } from "@tanstack/react-query";

export const v2AccountsWealthListInfiniteQueryKey = ({ account_address }: { account_address: V2AccountsWealthListPathParams["account_address"] }, params: V2AccountsWealthListQueryParams) => [{ url: '/v2/accounts/:account_address/wealth/', params: {account_address:account_address} }, ...(params ? [params] : [])] as const

export type V2AccountsWealthListInfiniteQueryKey = ReturnType<typeof v2AccountsWealthListInfiniteQueryKey>

/**
 * {@link /v2/accounts/:account_address/wealth/}
 */
export async function v2AccountsWealthListInfinite({ account_address, params }: { account_address: V2AccountsWealthListPathParams["account_address"]; params: V2AccountsWealthListQueryParams }, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<V2AccountsWealthListQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/v2/accounts/${account_address}/wealth/`, params, ... requestConfig })  
  return v2AccountsWealthListQueryResponseSchema.parse(res.data)
}

export function v2AccountsWealthListInfiniteQueryOptions({ account_address, params }: { account_address: V2AccountsWealthListPathParams["account_address"]; params: V2AccountsWealthListQueryParams }, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = v2AccountsWealthListInfiniteQueryKey({ account_address }, params)
  return infiniteQueryOptions<V2AccountsWealthListQueryResponse, ResponseErrorConfig<Error>, V2AccountsWealthListQueryResponse, typeof queryKey, number>({
   enabled: !!(account_address&& params),
   queryKey,
   queryFn: async ({ signal, pageParam }) => {
      config.signal = signal
    
      if (!params) {
       params = { }
      }
      params['page'] = pageParam as unknown as V2AccountsWealthListQueryParams['page']
      return v2AccountsWealthListInfinite({ account_address, params }, config)
   },
   initialPageParam: 0,
  getNextPageParam: (lastPage) => lastPage['nextPage'],
  getPreviousPageParam: (firstPage) => firstPage['nextPage']
  })
}

/**
 * {@link /v2/accounts/:account_address/wealth/}
 */
export function useV2AccountsWealthListInfinite<TData = InfiniteData<V2AccountsWealthListQueryResponse>, TQueryData = V2AccountsWealthListQueryResponse, TQueryKey extends QueryKey = V2AccountsWealthListInfiniteQueryKey>({ account_address, params }: { account_address: V2AccountsWealthListPathParams["account_address"]; params: V2AccountsWealthListQueryParams }, options: 
{
  query?: Partial<InfiniteQueryObserverOptions<V2AccountsWealthListQueryResponse, ResponseErrorConfig<Error>, TQueryData, TQueryKey, TQueryData>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? v2AccountsWealthListInfiniteQueryKey({ account_address }, params)

  const query = useInfiniteQuery({
   ...v2AccountsWealthListInfiniteQueryOptions({ account_address, params }, config),
   queryKey,
   ...queryOptions
  } as unknown as InfiniteQueryObserverOptions, queryClient) as UseInfiniteQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}