/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { V1DiscoverLuckySpinListQueryResponse, V1DiscoverLuckySpinListQueryParams } from "../types/V1DiscoverLuckySpinList.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { v1DiscoverLuckySpinListQueryResponseSchema } from "../zod/v1DiscoverLuckySpinListSchema.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const v1DiscoverLuckySpinListSuspenseQueryKey = (params: V1DiscoverLuckySpinListQueryParams) => [{ url: '/v1/discover/lucky-spin/' }, ...(params ? [params] : [])] as const

export type V1DiscoverLuckySpinListSuspenseQueryKey = ReturnType<typeof v1DiscoverLuckySpinListSuspenseQueryKey>

/**
 * @description Step 1: Lucky Spin Commitment PhaseReturns commitment transactions (user 0 ALGO + distributor fee coverage) without revealing prize.Query Parameters:- address (required): User's Algorand address- game_id (optional): UUID of specific game to play. If not provided, uses the first active game.
 * {@link /v1/discover/lucky-spin/}
 */
export async function v1DiscoverLuckySpinListSuspense({ params }: { params: V1DiscoverLuckySpinListQueryParams }, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<V1DiscoverLuckySpinListQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/v1/discover/lucky-spin/`, params, ... requestConfig })  
  return v1DiscoverLuckySpinListQueryResponseSchema.parse(res.data)
}

export function v1DiscoverLuckySpinListSuspenseQueryOptions({ params }: { params: V1DiscoverLuckySpinListQueryParams }, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = v1DiscoverLuckySpinListSuspenseQueryKey(params)
  return queryOptions<V1DiscoverLuckySpinListQueryResponse, ResponseErrorConfig<Error>, V1DiscoverLuckySpinListQueryResponse, typeof queryKey>({
   enabled: !!(params),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return v1DiscoverLuckySpinListSuspense({ params }, config)
   },
  })
}

/**
 * @description Step 1: Lucky Spin Commitment PhaseReturns commitment transactions (user 0 ALGO + distributor fee coverage) without revealing prize.Query Parameters:- address (required): User's Algorand address- game_id (optional): UUID of specific game to play. If not provided, uses the first active game.
 * {@link /v1/discover/lucky-spin/}
 */
export function useV1DiscoverLuckySpinListSuspense<TData = V1DiscoverLuckySpinListQueryResponse, TQueryKey extends QueryKey = V1DiscoverLuckySpinListSuspenseQueryKey>({ params }: { params: V1DiscoverLuckySpinListQueryParams }, options: 
{
  query?: Partial<UseSuspenseQueryOptions<V1DiscoverLuckySpinListQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? v1DiscoverLuckySpinListSuspenseQueryKey(params)

  const query = useSuspenseQuery({
   ...v1DiscoverLuckySpinListSuspenseQueryOptions({ params }, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}