/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { V2AccountsWealthListQueryResponse, V2AccountsWealthListPathParams, V2AccountsWealthListQueryParams } from "../types/V2AccountsWealthList.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { v2AccountsWealthListQueryResponseSchema } from "../zod/v2AccountsWealthListSchema.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const v2AccountsWealthListQueryKey = ({ account_address }: { account_address: V2AccountsWealthListPathParams["account_address"] }, params: V2AccountsWealthListQueryParams) => [{ url: '/v2/accounts/:account_address/wealth/', params: {account_address:account_address} }, ...(params ? [params] : [])] as const

export type V2AccountsWealthListQueryKey = ReturnType<typeof v2AccountsWealthListQueryKey>

/**
 * {@link /v2/accounts/:account_address/wealth/}
 */
export async function v2AccountsWealthList({ account_address, params }: { account_address: V2AccountsWealthListPathParams["account_address"]; params: V2AccountsWealthListQueryParams }, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<V2AccountsWealthListQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/v2/accounts/${account_address}/wealth/`, params, ... requestConfig })  
  return v2AccountsWealthListQueryResponseSchema.parse(res.data)
}

export function v2AccountsWealthListQueryOptions({ account_address, params }: { account_address: V2AccountsWealthListPathParams["account_address"]; params: V2AccountsWealthListQueryParams }, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = v2AccountsWealthListQueryKey({ account_address }, params)
  return queryOptions<V2AccountsWealthListQueryResponse, ResponseErrorConfig<Error>, V2AccountsWealthListQueryResponse, typeof queryKey>({
   enabled: !!(account_address&& params),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return v2AccountsWealthList({ account_address, params }, config)
   },
  })
}

/**
 * {@link /v2/accounts/:account_address/wealth/}
 */
export function useV2AccountsWealthList<TData = V2AccountsWealthListQueryResponse, TQueryData = V2AccountsWealthListQueryResponse, TQueryKey extends QueryKey = V2AccountsWealthListQueryKey>({ account_address, params }: { account_address: V2AccountsWealthListPathParams["account_address"]; params: V2AccountsWealthListQueryParams }, options: 
{
  query?: Partial<QueryObserverOptions<V2AccountsWealthListQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? v2AccountsWealthListQueryKey({ account_address }, params)

  const query = useQuery({
   ...v2AccountsWealthListQueryOptions({ account_address, params }, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}