/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { V1AccountsFastLookupReadQueryResponse, V1AccountsFastLookupReadPathParams } from "../types/V1AccountsFastLookupRead.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { v1AccountsFastLookupReadQueryResponseSchema } from "../zod/v1AccountsFastLookupReadSchema.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const v1AccountsFastLookupReadQueryKey = ({ account_address }: { account_address: V1AccountsFastLookupReadPathParams["account_address"] }) => [{ url: '/v1/accounts/fast-lookup/:account_address/', params: {account_address:account_address} }] as const

export type V1AccountsFastLookupReadQueryKey = ReturnType<typeof v1AccountsFastLookupReadQueryKey>

/**
 * @description - Uses a limited number of assets for faster lookup.- calculation_type is "exact" if all assets are considered, otherwise "min"
 * @summary Quickly looks up account information and calculates asset values.
 * {@link /v1/accounts/fast-lookup/:account_address/}
 */
export async function v1AccountsFastLookupRead({ account_address }: { account_address: V1AccountsFastLookupReadPathParams["account_address"] }, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<V1AccountsFastLookupReadQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/v1/accounts/fast-lookup/${account_address}/`, ... requestConfig })  
  return v1AccountsFastLookupReadQueryResponseSchema.parse(res.data)
}

export function v1AccountsFastLookupReadQueryOptions({ account_address }: { account_address: V1AccountsFastLookupReadPathParams["account_address"] }, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = v1AccountsFastLookupReadQueryKey({ account_address })
  return queryOptions<V1AccountsFastLookupReadQueryResponse, ResponseErrorConfig<Error>, V1AccountsFastLookupReadQueryResponse, typeof queryKey>({
   enabled: !!(account_address),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return v1AccountsFastLookupRead({ account_address }, config)
   },
  })
}

/**
 * @description - Uses a limited number of assets for faster lookup.- calculation_type is "exact" if all assets are considered, otherwise "min"
 * @summary Quickly looks up account information and calculates asset values.
 * {@link /v1/accounts/fast-lookup/:account_address/}
 */
export function useV1AccountsFastLookupRead<TData = V1AccountsFastLookupReadQueryResponse, TQueryData = V1AccountsFastLookupReadQueryResponse, TQueryKey extends QueryKey = V1AccountsFastLookupReadQueryKey>({ account_address }: { account_address: V1AccountsFastLookupReadPathParams["account_address"] }, options: 
{
  query?: Partial<QueryObserverOptions<V1AccountsFastLookupReadQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? v1AccountsFastLookupReadQueryKey({ account_address })

  const query = useQuery({
   ...v1AccountsFastLookupReadQueryOptions({ account_address }, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}