/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { V1AccountsCollectibleAssetsListQueryResponse, V1AccountsCollectibleAssetsListPathParams, V1AccountsCollectibleAssetsListQueryParams } from "../types/V1AccountsCollectibleAssetsList.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { InfiniteData, QueryKey, QueryClient, InfiniteQueryObserverOptions, UseInfiniteQueryResult } from "@tanstack/react-query";
import { v1AccountsCollectibleAssetsListQueryResponseSchema } from "../zod/v1AccountsCollectibleAssetsListSchema.ts";
import { infiniteQueryOptions, useInfiniteQuery } from "@tanstack/react-query";

export const v1AccountsCollectibleAssetsListInfiniteQueryKey = ({ account_address }: { account_address: V1AccountsCollectibleAssetsListPathParams["account_address"] }, params?: V1AccountsCollectibleAssetsListQueryParams) => [{ url: '/v1/accounts/:account_address/collectible-assets/', params: {account_address:account_address} }, ...(params ? [params] : [])] as const

export type V1AccountsCollectibleAssetsListInfiniteQueryKey = ReturnType<typeof v1AccountsCollectibleAssetsListInfiniteQueryKey>

/**
 * @description Ordered by asset_id DESC.
 * {@link /v1/accounts/:account_address/collectible-assets/}
 */
export async function v1AccountsCollectibleAssetsListInfinite({ account_address, params }: { account_address: V1AccountsCollectibleAssetsListPathParams["account_address"]; params?: V1AccountsCollectibleAssetsListQueryParams }, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<V1AccountsCollectibleAssetsListQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/v1/accounts/${account_address}/collectible-assets/`, params, ... requestConfig })  
  return v1AccountsCollectibleAssetsListQueryResponseSchema.parse(res.data)
}

export function v1AccountsCollectibleAssetsListInfiniteQueryOptions({ account_address, params }: { account_address: V1AccountsCollectibleAssetsListPathParams["account_address"]; params?: V1AccountsCollectibleAssetsListQueryParams }, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = v1AccountsCollectibleAssetsListInfiniteQueryKey({ account_address }, params)
  return infiniteQueryOptions<V1AccountsCollectibleAssetsListQueryResponse, ResponseErrorConfig<Error>, V1AccountsCollectibleAssetsListQueryResponse, typeof queryKey, number>({
   enabled: !!(account_address),
   queryKey,
   queryFn: async ({ signal, pageParam }) => {
      config.signal = signal
    
      if (!params) {
       params = { }
      }
      params['page'] = pageParam as unknown as V1AccountsCollectibleAssetsListQueryParams['page']
      return v1AccountsCollectibleAssetsListInfinite({ account_address, params }, config)
   },
   initialPageParam: 0,
  getNextPageParam: (lastPage) => lastPage['nextPage'],
  getPreviousPageParam: (firstPage) => firstPage['nextPage']
  })
}

/**
 * @description Ordered by asset_id DESC.
 * {@link /v1/accounts/:account_address/collectible-assets/}
 */
export function useV1AccountsCollectibleAssetsListInfinite<TData = InfiniteData<V1AccountsCollectibleAssetsListQueryResponse>, TQueryData = V1AccountsCollectibleAssetsListQueryResponse, TQueryKey extends QueryKey = V1AccountsCollectibleAssetsListInfiniteQueryKey>({ account_address, params }: { account_address: V1AccountsCollectibleAssetsListPathParams["account_address"]; params?: V1AccountsCollectibleAssetsListQueryParams }, options: 
{
  query?: Partial<InfiniteQueryObserverOptions<V1AccountsCollectibleAssetsListQueryResponse, ResponseErrorConfig<Error>, TQueryData, TQueryKey, TQueryData>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? v1AccountsCollectibleAssetsListInfiniteQueryKey({ account_address }, params)

  const query = useInfiniteQuery({
   ...v1AccountsCollectibleAssetsListInfiniteQueryOptions({ account_address, params }, config),
   queryKey,
   ...queryOptions
  } as unknown as InfiniteQueryObserverOptions, queryClient) as UseInfiniteQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}