/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { V1OnrampServicesMeldPaymentMethodsListQueryResponse, V1OnrampServicesMeldPaymentMethodsListQueryParams } from "../types/V1OnrampServicesMeldPaymentMethodsList.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { v1OnrampServicesMeldPaymentMethodsListQueryResponseSchema } from "../zod/v1OnrampServicesMeldPaymentMethodsListSchema.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const v1OnrampServicesMeldPaymentMethodsListSuspenseQueryKey = (params: V1OnrampServicesMeldPaymentMethodsListQueryParams) => [{ url: '/v1/onramp-services/meld/payment-methods/' }, ...(params ? [params] : [])] as const

export type V1OnrampServicesMeldPaymentMethodsListSuspenseQueryKey = ReturnType<typeof v1OnrampServicesMeldPaymentMethodsListSuspenseQueryKey>

/**
 * @description Returns a list of available payment methods via Meld service.
 * @summary Meld Payment Methods View
 * {@link /v1/onramp-services/meld/payment-methods/}
 */
export async function v1OnrampServicesMeldPaymentMethodsListSuspense({ params }: { params: V1OnrampServicesMeldPaymentMethodsListQueryParams }, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<V1OnrampServicesMeldPaymentMethodsListQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/v1/onramp-services/meld/payment-methods/`, params, ... requestConfig })  
  return v1OnrampServicesMeldPaymentMethodsListQueryResponseSchema.parse(res.data)
}

export function v1OnrampServicesMeldPaymentMethodsListSuspenseQueryOptions({ params }: { params: V1OnrampServicesMeldPaymentMethodsListQueryParams }, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = v1OnrampServicesMeldPaymentMethodsListSuspenseQueryKey(params)
  return queryOptions<V1OnrampServicesMeldPaymentMethodsListQueryResponse, ResponseErrorConfig<Error>, V1OnrampServicesMeldPaymentMethodsListQueryResponse, typeof queryKey>({
   enabled: !!(params),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return v1OnrampServicesMeldPaymentMethodsListSuspense({ params }, config)
   },
  })
}

/**
 * @description Returns a list of available payment methods via Meld service.
 * @summary Meld Payment Methods View
 * {@link /v1/onramp-services/meld/payment-methods/}
 */
export function useV1OnrampServicesMeldPaymentMethodsListSuspense<TData = V1OnrampServicesMeldPaymentMethodsListQueryResponse, TQueryKey extends QueryKey = V1OnrampServicesMeldPaymentMethodsListSuspenseQueryKey>({ params }: { params: V1OnrampServicesMeldPaymentMethodsListQueryParams }, options: 
{
  query?: Partial<UseSuspenseQueryOptions<V1OnrampServicesMeldPaymentMethodsListQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? v1OnrampServicesMeldPaymentMethodsListSuspenseQueryKey(params)

  const query = useSuspenseQuery({
   ...v1OnrampServicesMeldPaymentMethodsListSuspenseQueryOptions({ params }, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}