/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { V1AssetRequestsCreateMutationRequest, V1AssetRequestsCreateMutationResponse } from "../types/V1AssetRequestsCreate.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, QueryClient } from "@tanstack/react-query";
import { v1AssetRequestsCreateMutationResponseSchema, v1AssetRequestsCreateMutationRequestSchema } from "../zod/v1AssetRequestsCreateSchema.ts";
import { useMutation } from "@tanstack/react-query";

export const v1AssetRequestsCreateMutationKey = () => [{ url: '/v1/asset-requests/' }] as const

export type V1AssetRequestsCreateMutationKey = ReturnType<typeof v1AssetRequestsCreateMutationKey>

/**
 * @description This view keeps sender, receiver, and asset information and notifies the receiver that the sender wants to send this asset to you.
 * @summary Create Asset Request
 * {@link /v1/asset-requests/}
 */
export async function v1AssetRequestsCreate({ data }: { data: V1AssetRequestsCreateMutationRequest }, config: Partial<RequestConfig<V1AssetRequestsCreateMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = v1AssetRequestsCreateMutationRequestSchema.parse(data)  
  
  const res = await request<V1AssetRequestsCreateMutationResponse, ResponseErrorConfig<Error>, V1AssetRequestsCreateMutationRequest>({ method : "POST", url : `/v1/asset-requests/`, data : requestData, ... requestConfig })  
  return v1AssetRequestsCreateMutationResponseSchema.parse(res.data)
}

/**
 * @description This view keeps sender, receiver, and asset information and notifies the receiver that the sender wants to send this asset to you.
 * @summary Create Asset Request
 * {@link /v1/asset-requests/}
 */
export function useV1AssetRequestsCreate<TContext>(options: 
{
  mutation?: UseMutationOptions<V1AssetRequestsCreateMutationResponse, ResponseErrorConfig<Error>, {data: V1AssetRequestsCreateMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<V1AssetRequestsCreateMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? v1AssetRequestsCreateMutationKey()

  return useMutation<V1AssetRequestsCreateMutationResponse, ResponseErrorConfig<Error>, {data: V1AssetRequestsCreateMutationRequest}, TContext>({
    mutationFn: async({ data }) => {
      return v1AssetRequestsCreate({ data }, config)
    },
    mutationKey,
    ...mutationOptions
  }, queryClient)
}