/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { V1DiscoverFeaturedProjectsListQueryResponse, V1DiscoverFeaturedProjectsListQueryParams } from "../types/V1DiscoverFeaturedProjectsList.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { v1DiscoverFeaturedProjectsListQueryResponseSchema } from "../zod/v1DiscoverFeaturedProjectsListSchema.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const v1DiscoverFeaturedProjectsListSuspenseQueryKey = (params?: V1DiscoverFeaturedProjectsListQueryParams) => [{ url: '/v1/discover/featured-projects/' }, ...(params ? [params] : [])] as const

export type V1DiscoverFeaturedProjectsListSuspenseQueryKey = ReturnType<typeof v1DiscoverFeaturedProjectsListSuspenseQueryKey>

/**
 * {@link /v1/discover/featured-projects/}
 */
export async function v1DiscoverFeaturedProjectsListSuspense({ params }: { params?: V1DiscoverFeaturedProjectsListQueryParams }, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<V1DiscoverFeaturedProjectsListQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/v1/discover/featured-projects/`, params, ... requestConfig })  
  return v1DiscoverFeaturedProjectsListQueryResponseSchema.parse(res.data)
}

export function v1DiscoverFeaturedProjectsListSuspenseQueryOptions({ params }: { params?: V1DiscoverFeaturedProjectsListQueryParams }, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = v1DiscoverFeaturedProjectsListSuspenseQueryKey(params)
  return queryOptions<V1DiscoverFeaturedProjectsListQueryResponse, ResponseErrorConfig<Error>, V1DiscoverFeaturedProjectsListQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return v1DiscoverFeaturedProjectsListSuspense({ params }, config)
   },
  })
}

/**
 * {@link /v1/discover/featured-projects/}
 */
export function useV1DiscoverFeaturedProjectsListSuspense<TData = V1DiscoverFeaturedProjectsListQueryResponse, TQueryKey extends QueryKey = V1DiscoverFeaturedProjectsListSuspenseQueryKey>({ params }: { params?: V1DiscoverFeaturedProjectsListQueryParams }, options: 
{
  query?: Partial<UseSuspenseQueryOptions<V1DiscoverFeaturedProjectsListQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? v1DiscoverFeaturedProjectsListSuspenseQueryKey(params)

  const query = useSuspenseQuery({
   ...v1DiscoverFeaturedProjectsListSuspenseQueryOptions({ params }, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}