/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { V2DevicesNotificationsListQueryResponse, V2DevicesNotificationsListPathParams, V2DevicesNotificationsListQueryParams } from "../types/V2DevicesNotificationsList.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { InfiniteData, QueryKey, QueryClient, InfiniteQueryObserverOptions, UseInfiniteQueryResult } from "@tanstack/react-query";
import { v2DevicesNotificationsListQueryResponseSchema } from "../zod/v2DevicesNotificationsListSchema.ts";
import { infiniteQueryOptions, useInfiniteQuery } from "@tanstack/react-query";

export const v2DevicesNotificationsListInfiniteQueryKey = ({ device_id }: { device_id: V2DevicesNotificationsListPathParams["device_id"] }, params?: V2DevicesNotificationsListQueryParams) => [{ url: '/v2/devices/:device_id/notifications/', params: {device_id:device_id} }, ...(params ? [params] : [])] as const

export type V2DevicesNotificationsListInfiniteQueryKey = ReturnType<typeof v2DevicesNotificationsListInfiniteQueryKey>

/**
 * {@link /v2/devices/:device_id/notifications/}
 */
export async function v2DevicesNotificationsListInfinite({ device_id, params }: { device_id: V2DevicesNotificationsListPathParams["device_id"]; params?: V2DevicesNotificationsListQueryParams }, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<V2DevicesNotificationsListQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/v2/devices/${device_id}/notifications/`, params, ... requestConfig })  
  return v2DevicesNotificationsListQueryResponseSchema.parse(res.data)
}

export function v2DevicesNotificationsListInfiniteQueryOptions({ device_id, params }: { device_id: V2DevicesNotificationsListPathParams["device_id"]; params?: V2DevicesNotificationsListQueryParams }, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = v2DevicesNotificationsListInfiniteQueryKey({ device_id }, params)
  return infiniteQueryOptions<V2DevicesNotificationsListQueryResponse, ResponseErrorConfig<Error>, V2DevicesNotificationsListQueryResponse, typeof queryKey, number>({
   enabled: !!(device_id),
   queryKey,
   queryFn: async ({ signal, pageParam }) => {
      config.signal = signal
    
      if (!params) {
       params = { }
      }
      params['page'] = pageParam as unknown as V2DevicesNotificationsListQueryParams['page']
      return v2DevicesNotificationsListInfinite({ device_id, params }, config)
   },
   initialPageParam: 0,
  getNextPageParam: (lastPage) => lastPage['nextPage'],
  getPreviousPageParam: (firstPage) => firstPage['nextPage']
  })
}

/**
 * {@link /v2/devices/:device_id/notifications/}
 */
export function useV2DevicesNotificationsListInfinite<TData = InfiniteData<V2DevicesNotificationsListQueryResponse>, TQueryData = V2DevicesNotificationsListQueryResponse, TQueryKey extends QueryKey = V2DevicesNotificationsListInfiniteQueryKey>({ device_id, params }: { device_id: V2DevicesNotificationsListPathParams["device_id"]; params?: V2DevicesNotificationsListQueryParams }, options: 
{
  query?: Partial<InfiniteQueryObserverOptions<V2DevicesNotificationsListQueryResponse, ResponseErrorConfig<Error>, TQueryData, TQueryKey, TQueryData>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? v2DevicesNotificationsListInfiniteQueryKey({ device_id }, params)

  const query = useInfiniteQuery({
   ...v2DevicesNotificationsListInfiniteQueryOptions({ device_id, params }, config),
   queryKey,
   ...queryOptions
  } as unknown as InfiniteQueryObserverOptions, queryClient) as UseInfiniteQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}