/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { V1AsaInboxesSummarySendFlowReadQueryResponse, V1AsaInboxesSummarySendFlowReadPathParams, V1AsaInboxesSummarySendFlowReadQueryParams } from "../types/V1AsaInboxesSummarySendFlowRead.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { v1AsaInboxesSummarySendFlowReadQueryResponseSchema } from "../zod/v1AsaInboxesSummarySendFlowReadSchema.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const v1AsaInboxesSummarySendFlowReadQueryKey = ({ asset_id, receiver_address }: { asset_id: V1AsaInboxesSummarySendFlowReadPathParams["asset_id"]; receiver_address: V1AsaInboxesSummarySendFlowReadPathParams["receiver_address"] }, params?: V1AsaInboxesSummarySendFlowReadQueryParams) => [{ url: '/v1/asa-inboxes/summary/send-flow/:receiver_address/:asset_id/', params: {receiver_address:receiver_address,asset_id:asset_id} }, ...(params ? [params] : [])] as const

export type V1AsaInboxesSummarySendFlowReadQueryKey = ReturnType<typeof v1AsaInboxesSummarySendFlowReadQueryKey>

/**
 * {@link /v1/asa-inboxes/summary/send-flow/:receiver_address/:asset_id/}
 */
export async function v1AsaInboxesSummarySendFlowRead({ asset_id, receiver_address, params }: { asset_id: V1AsaInboxesSummarySendFlowReadPathParams["asset_id"]; receiver_address: V1AsaInboxesSummarySendFlowReadPathParams["receiver_address"]; params?: V1AsaInboxesSummarySendFlowReadQueryParams }, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<V1AsaInboxesSummarySendFlowReadQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/v1/asa-inboxes/summary/send-flow/${receiver_address}/${asset_id}/`, params, ... requestConfig })  
  return v1AsaInboxesSummarySendFlowReadQueryResponseSchema.parse(res.data)
}

export function v1AsaInboxesSummarySendFlowReadQueryOptions({ asset_id, receiver_address, params }: { asset_id: V1AsaInboxesSummarySendFlowReadPathParams["asset_id"]; receiver_address: V1AsaInboxesSummarySendFlowReadPathParams["receiver_address"]; params?: V1AsaInboxesSummarySendFlowReadQueryParams }, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = v1AsaInboxesSummarySendFlowReadQueryKey({ asset_id, receiver_address }, params)
  return queryOptions<V1AsaInboxesSummarySendFlowReadQueryResponse, ResponseErrorConfig<Error>, V1AsaInboxesSummarySendFlowReadQueryResponse, typeof queryKey>({
   enabled: !!(asset_id&& receiver_address),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return v1AsaInboxesSummarySendFlowRead({ asset_id, receiver_address, params }, config)
   },
  })
}

/**
 * {@link /v1/asa-inboxes/summary/send-flow/:receiver_address/:asset_id/}
 */
export function useV1AsaInboxesSummarySendFlowRead<TData = V1AsaInboxesSummarySendFlowReadQueryResponse, TQueryData = V1AsaInboxesSummarySendFlowReadQueryResponse, TQueryKey extends QueryKey = V1AsaInboxesSummarySendFlowReadQueryKey>({ asset_id, receiver_address, params }: { asset_id: V1AsaInboxesSummarySendFlowReadPathParams["asset_id"]; receiver_address: V1AsaInboxesSummarySendFlowReadPathParams["receiver_address"]; params?: V1AsaInboxesSummarySendFlowReadQueryParams }, options: 
{
  query?: Partial<QueryObserverOptions<V1AsaInboxesSummarySendFlowReadQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? v1AsaInboxesSummarySendFlowReadQueryKey({ asset_id, receiver_address }, params)

  const query = useQuery({
   ...v1AsaInboxesSummarySendFlowReadQueryOptions({ asset_id, receiver_address, params }, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}