/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { V1DiscoverNewsReadQueryResponse, V1DiscoverNewsReadPathParams } from "../types/V1DiscoverNewsRead.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { v1DiscoverNewsReadQueryResponseSchema } from "../zod/v1DiscoverNewsReadSchema.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const v1DiscoverNewsReadQueryKey = ({ id }: { id: V1DiscoverNewsReadPathParams["id"] }) => [{ url: '/v1/discover/news/:id/', params: {id:id} }] as const

export type V1DiscoverNewsReadQueryKey = ReturnType<typeof v1DiscoverNewsReadQueryKey>

/**
 * {@link /v1/discover/news/:id/}
 */
export async function v1DiscoverNewsRead({ id }: { id: V1DiscoverNewsReadPathParams["id"] }, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<V1DiscoverNewsReadQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/v1/discover/news/${id}/`, ... requestConfig })  
  return v1DiscoverNewsReadQueryResponseSchema.parse(res.data)
}

export function v1DiscoverNewsReadQueryOptions({ id }: { id: V1DiscoverNewsReadPathParams["id"] }, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = v1DiscoverNewsReadQueryKey({ id })
  return queryOptions<V1DiscoverNewsReadQueryResponse, ResponseErrorConfig<Error>, V1DiscoverNewsReadQueryResponse, typeof queryKey>({
   enabled: !!(id),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return v1DiscoverNewsRead({ id }, config)
   },
  })
}

/**
 * {@link /v1/discover/news/:id/}
 */
export function useV1DiscoverNewsRead<TData = V1DiscoverNewsReadQueryResponse, TQueryData = V1DiscoverNewsReadQueryResponse, TQueryKey extends QueryKey = V1DiscoverNewsReadQueryKey>({ id }: { id: V1DiscoverNewsReadPathParams["id"] }, options: 
{
  query?: Partial<QueryObserverOptions<V1DiscoverNewsReadQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? v1DiscoverNewsReadQueryKey({ id })

  const query = useQuery({
   ...v1DiscoverNewsReadQueryOptions({ id }, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}