/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { V1DevicesAssetsPriceWatchAssetStatusListQueryResponse, V1DevicesAssetsPriceWatchAssetStatusListPathParams } from "../types/V1DevicesAssetsPriceWatchAssetStatusList.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { v1DevicesAssetsPriceWatchAssetStatusListQueryResponseSchema } from "../zod/v1DevicesAssetsPriceWatchAssetStatusListSchema.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const v1DevicesAssetsPriceWatchAssetStatusListSuspenseQueryKey = ({ asset_id, device_id }: { asset_id: V1DevicesAssetsPriceWatchAssetStatusListPathParams["asset_id"]; device_id: V1DevicesAssetsPriceWatchAssetStatusListPathParams["device_id"] }) => [{ url: '/v1/devices/:device_id/assets/:asset_id/price-watch-asset-status/', params: {device_id:device_id,asset_id:asset_id} }] as const

export type V1DevicesAssetsPriceWatchAssetStatusListSuspenseQueryKey = ReturnType<typeof v1DevicesAssetsPriceWatchAssetStatusListSuspenseQueryKey>

/**
 * @description This device authenticated endpoint returns just is price watch asset or not for the authenticated device.
 * @summary Price Watch Asset Status
 * {@link /v1/devices/:device_id/assets/:asset_id/price-watch-asset-status/}
 */
export async function v1DevicesAssetsPriceWatchAssetStatusListSuspense({ asset_id, device_id }: { asset_id: V1DevicesAssetsPriceWatchAssetStatusListPathParams["asset_id"]; device_id: V1DevicesAssetsPriceWatchAssetStatusListPathParams["device_id"] }, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<V1DevicesAssetsPriceWatchAssetStatusListQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/v1/devices/${device_id}/assets/${asset_id}/price-watch-asset-status/`, ... requestConfig })  
  return v1DevicesAssetsPriceWatchAssetStatusListQueryResponseSchema.parse(res.data)
}

export function v1DevicesAssetsPriceWatchAssetStatusListSuspenseQueryOptions({ asset_id, device_id }: { asset_id: V1DevicesAssetsPriceWatchAssetStatusListPathParams["asset_id"]; device_id: V1DevicesAssetsPriceWatchAssetStatusListPathParams["device_id"] }, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = v1DevicesAssetsPriceWatchAssetStatusListSuspenseQueryKey({ asset_id, device_id })
  return queryOptions<V1DevicesAssetsPriceWatchAssetStatusListQueryResponse, ResponseErrorConfig<Error>, V1DevicesAssetsPriceWatchAssetStatusListQueryResponse, typeof queryKey>({
   enabled: !!(asset_id&& device_id),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return v1DevicesAssetsPriceWatchAssetStatusListSuspense({ asset_id, device_id }, config)
   },
  })
}

/**
 * @description This device authenticated endpoint returns just is price watch asset or not for the authenticated device.
 * @summary Price Watch Asset Status
 * {@link /v1/devices/:device_id/assets/:asset_id/price-watch-asset-status/}
 */
export function useV1DevicesAssetsPriceWatchAssetStatusListSuspense<TData = V1DevicesAssetsPriceWatchAssetStatusListQueryResponse, TQueryKey extends QueryKey = V1DevicesAssetsPriceWatchAssetStatusListSuspenseQueryKey>({ asset_id, device_id }: { asset_id: V1DevicesAssetsPriceWatchAssetStatusListPathParams["asset_id"]; device_id: V1DevicesAssetsPriceWatchAssetStatusListPathParams["device_id"] }, options: 
{
  query?: Partial<UseSuspenseQueryOptions<V1DevicesAssetsPriceWatchAssetStatusListQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? v1DevicesAssetsPriceWatchAssetStatusListSuspenseQueryKey({ asset_id, device_id })

  const query = useSuspenseQuery({
   ...v1DevicesAssetsPriceWatchAssetStatusListSuspenseQueryOptions({ asset_id, device_id }, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}