/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { V1DiscoverHomeFeaturedProjectsListQueryResponse, V1DiscoverHomeFeaturedProjectsListQueryParams } from "../types/V1DiscoverHomeFeaturedProjectsList.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { InfiniteData, QueryKey, QueryClient, InfiniteQueryObserverOptions, UseInfiniteQueryResult } from "@tanstack/react-query";
import { v1DiscoverHomeFeaturedProjectsListQueryResponseSchema } from "../zod/v1DiscoverHomeFeaturedProjectsListSchema.ts";
import { infiniteQueryOptions, useInfiniteQuery } from "@tanstack/react-query";

export const v1DiscoverHomeFeaturedProjectsListInfiniteQueryKey = (params?: V1DiscoverHomeFeaturedProjectsListQueryParams) => [{ url: '/v1/discover/home-featured-projects/' }, ...(params ? [params] : [])] as const

export type V1DiscoverHomeFeaturedProjectsListInfiniteQueryKey = ReturnType<typeof v1DiscoverHomeFeaturedProjectsListInfiniteQueryKey>

/**
 * {@link /v1/discover/home-featured-projects/}
 */
export async function v1DiscoverHomeFeaturedProjectsListInfinite({ params }: { params?: V1DiscoverHomeFeaturedProjectsListQueryParams }, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<V1DiscoverHomeFeaturedProjectsListQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/v1/discover/home-featured-projects/`, params, ... requestConfig })  
  return v1DiscoverHomeFeaturedProjectsListQueryResponseSchema.parse(res.data)
}

export function v1DiscoverHomeFeaturedProjectsListInfiniteQueryOptions({ params }: { params?: V1DiscoverHomeFeaturedProjectsListQueryParams }, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = v1DiscoverHomeFeaturedProjectsListInfiniteQueryKey(params)
  return infiniteQueryOptions<V1DiscoverHomeFeaturedProjectsListQueryResponse, ResponseErrorConfig<Error>, V1DiscoverHomeFeaturedProjectsListQueryResponse, typeof queryKey, number>({
 
   queryKey,
   queryFn: async ({ signal, pageParam }) => {
      config.signal = signal
    
      if (!params) {
       params = { }
      }
      params['page'] = pageParam as unknown as V1DiscoverHomeFeaturedProjectsListQueryParams['page']
      return v1DiscoverHomeFeaturedProjectsListInfinite({ params }, config)
   },
   initialPageParam: 0,
  getNextPageParam: (lastPage) => lastPage['nextPage'],
  getPreviousPageParam: (firstPage) => firstPage['nextPage']
  })
}

/**
 * {@link /v1/discover/home-featured-projects/}
 */
export function useV1DiscoverHomeFeaturedProjectsListInfinite<TData = InfiniteData<V1DiscoverHomeFeaturedProjectsListQueryResponse>, TQueryData = V1DiscoverHomeFeaturedProjectsListQueryResponse, TQueryKey extends QueryKey = V1DiscoverHomeFeaturedProjectsListInfiniteQueryKey>({ params }: { params?: V1DiscoverHomeFeaturedProjectsListQueryParams }, options: 
{
  query?: Partial<InfiniteQueryObserverOptions<V1DiscoverHomeFeaturedProjectsListQueryResponse, ResponseErrorConfig<Error>, TQueryData, TQueryKey, TQueryData>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? v1DiscoverHomeFeaturedProjectsListInfiniteQueryKey(params)

  const query = useInfiniteQuery({
   ...v1DiscoverHomeFeaturedProjectsListInfiniteQueryOptions({ params }, config),
   queryKey,
   ...queryOptions
  } as unknown as InfiniteQueryObserverOptions, queryClient) as UseInfiniteQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}