/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { V1WalletWealthListQueryResponse, V1WalletWealthListQueryParams } from "../types/V1WalletWealthList.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { v1WalletWealthListQueryResponseSchema } from "../zod/v1WalletWealthListSchema.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const v1WalletWealthListSuspenseQueryKey = (params: V1WalletWealthListQueryParams) => [{ url: '/v1/wallet/wealth/' }, ...(params ? [params] : [])] as const

export type V1WalletWealthListSuspenseQueryKey = ReturnType<typeof v1WalletWealthListSuspenseQueryKey>

/**
 * {@link /v1/wallet/wealth/}
 */
export async function v1WalletWealthListSuspense({ params }: { params: V1WalletWealthListQueryParams }, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<V1WalletWealthListQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/v1/wallet/wealth/`, params, ... requestConfig })  
  return v1WalletWealthListQueryResponseSchema.parse(res.data)
}

export function v1WalletWealthListSuspenseQueryOptions({ params }: { params: V1WalletWealthListQueryParams }, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = v1WalletWealthListSuspenseQueryKey(params)
  return queryOptions<V1WalletWealthListQueryResponse, ResponseErrorConfig<Error>, V1WalletWealthListQueryResponse, typeof queryKey>({
   enabled: !!(params),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return v1WalletWealthListSuspense({ params }, config)
   },
  })
}

/**
 * {@link /v1/wallet/wealth/}
 */
export function useV1WalletWealthListSuspense<TData = V1WalletWealthListQueryResponse, TQueryKey extends QueryKey = V1WalletWealthListSuspenseQueryKey>({ params }: { params: V1WalletWealthListQueryParams }, options: 
{
  query?: Partial<UseSuspenseQueryOptions<V1WalletWealthListQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? v1WalletWealthListSuspenseQueryKey(params)

  const query = useSuspenseQuery({
   ...v1WalletWealthListSuspenseQueryOptions({ params }, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}