/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { V2DevicesMeReadQueryResponse } from "../types/V2DevicesMeRead.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { v2DevicesMeReadQueryResponseSchema } from "../zod/v2DevicesMeReadSchema.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const v2DevicesMeReadSuspenseQueryKey = () => [{ url: '/v2/devices/me/' }] as const

export type V2DevicesMeReadSuspenseQueryKey = ReturnType<typeof v2DevicesMeReadSuspenseQueryKey>

/**
 * {@link /v2/devices/me/}
 */
export async function v2DevicesMeReadSuspense(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<V2DevicesMeReadQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/v2/devices/me/`, ... requestConfig })  
  return v2DevicesMeReadQueryResponseSchema.parse(res.data)
}

export function v2DevicesMeReadSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = v2DevicesMeReadSuspenseQueryKey()
  return queryOptions<V2DevicesMeReadQueryResponse, ResponseErrorConfig<Error>, V2DevicesMeReadQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return v2DevicesMeReadSuspense(config)
   },
  })
}

/**
 * {@link /v2/devices/me/}
 */
export function useV2DevicesMeReadSuspense<TData = V2DevicesMeReadQueryResponse, TQueryKey extends QueryKey = V2DevicesMeReadSuspenseQueryKey>(options: 
{
  query?: Partial<UseSuspenseQueryOptions<V2DevicesMeReadQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? v2DevicesMeReadSuspenseQueryKey()

  const query = useSuspenseQuery({
   ...v2DevicesMeReadSuspenseQueryOptions(config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}