/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { V1SearchListQueryResponse, V1SearchListQueryParams } from "../types/V1SearchList.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { v1SearchListQueryResponseSchema } from "../zod/v1SearchListSchema.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const v1SearchListQueryKey = (params?: V1SearchListQueryParams) => [{ url: '/v1/search/' }, ...(params ? [params] : [])] as const

export type V1SearchListQueryKey = ReturnType<typeof v1SearchListQueryKey>

/**
 * @description Given query parameters:    - q (required)    - filter (optional)This view is used to find:    - transactions, assets, collections, addresses, blocks, applications, groups.
 * @summary Search View
 * {@link /v1/search/}
 */
export async function v1SearchList({ params }: { params?: V1SearchListQueryParams }, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<V1SearchListQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/v1/search/`, params, ... requestConfig })  
  return v1SearchListQueryResponseSchema.parse(res.data)
}

export function v1SearchListQueryOptions({ params }: { params?: V1SearchListQueryParams }, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = v1SearchListQueryKey(params)
  return queryOptions<V1SearchListQueryResponse, ResponseErrorConfig<Error>, V1SearchListQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return v1SearchList({ params }, config)
   },
  })
}

/**
 * @description Given query parameters:    - q (required)    - filter (optional)This view is used to find:    - transactions, assets, collections, addresses, blocks, applications, groups.
 * @summary Search View
 * {@link /v1/search/}
 */
export function useV1SearchList<TData = V1SearchListQueryResponse, TQueryData = V1SearchListQueryResponse, TQueryKey extends QueryKey = V1SearchListQueryKey>({ params }: { params?: V1SearchListQueryParams }, options: 
{
  query?: Partial<QueryObserverOptions<V1SearchListQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? v1SearchListQueryKey(params)

  const query = useQuery({
   ...v1SearchListQueryOptions({ params }, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}