/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1AsaInboxesSummarySendFlowReadQueryResponse } from "../types/V1AsaInboxesSummarySendFlowRead.ts";
import { http } from "msw";

export function v1AsaInboxesSummarySendFlowReadHandler(data?: V1AsaInboxesSummarySendFlowReadQueryResponse | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Response)) {
  return http.get('/v1/asa-inboxes/summary/send-flow/:receiver_address/:asset_id/', function handler(info) {
    if(typeof data === 'function') return data(info)

    return new Response(JSON.stringify(data), {
      status: 200,
        headers: {
        'Content-Type': 'application/json'
      },
    })
  })
}