/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1BackupsDeleteMutationResponse } from "../types/V1BackupsDelete.ts";
import { http } from "msw";

export function v1BackupsDeleteHandler(data?: V1BackupsDeleteMutationResponse | ((
        info: Parameters<Parameters<typeof http.delete>[1]>[0],
      ) => Response)) {
  return http.delete('/v1/backups/:id/', function handler(info) {
    if(typeof data === 'function') return data(info)

    return new Response(JSON.stringify(data), {
      status: 204,
    
    })
  })
}