/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1DevicesAssetsPriceWatchAssetStatusListQueryResponse } from "../types/V1DevicesAssetsPriceWatchAssetStatusList.ts";
import { http } from "msw";

export function v1DevicesAssetsPriceWatchAssetStatusListHandler(data?: V1DevicesAssetsPriceWatchAssetStatusListQueryResponse | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Response)) {
  return http.get('/v1/devices/:device_id/assets/:asset_id/price-watch-asset-status/', function handler(info) {
    if(typeof data === 'function') return data(info)

    return new Response(JSON.stringify(data), {
      status: 200,
    
    })
  })
}