/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1DevicesPartialUpdateMutationResponse } from "../types/V1DevicesPartialUpdate.ts";
import { http } from "msw";

export function v1DevicesPartialUpdateHandler(data?: V1DevicesPartialUpdateMutationResponse | ((
        info: Parameters<Parameters<typeof http.patch>[1]>[0],
      ) => Response)) {
  return http.patch('/v1/devices/:device_id/', function handler(info) {
    if(typeof data === 'function') return data(info)

    return new Response(JSON.stringify(data), {
      status: 200,
        headers: {
        'Content-Type': 'application/json'
      },
    })
  })
}