/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V1DiscoverNftCollectionsListQueryResponse } from "../types/V1DiscoverNftCollectionsList.ts";
import { http } from "msw";

export function v1DiscoverNftCollectionsListHandler(data?: V1DiscoverNftCollectionsListQueryResponse | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Response)) {
  return http.get('/v1/discover/nft/collections/', function handler(info) {
    if(typeof data === 'function') return data(info)

    return new Response(JSON.stringify(data), {
      status: 200,
        headers: {
        'Content-Type': 'application/json'
      },
    })
  })
}