/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { V2AccountsAssetsBalanceHistoryListQueryResponse } from "../types/V2AccountsAssetsBalanceHistoryList.ts";
import { http } from "msw";

export function v2AccountsAssetsBalanceHistoryListHandler(data?: V2AccountsAssetsBalanceHistoryListQueryResponse | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Response)) {
  return http.get('/v2/accounts/:account_address/assets/:asset_id/balance-history/', function handler(info) {
    if(typeof data === 'function') return data(info)

    return new Response(JSON.stringify(data), {
      status: 200,
    
    })
  })
}