#!/bin/bash

# tools/generate-config.sh
# Generates a TypeScript configuration file from environment variables.
# This script is intended to be used in both local and CI environments.

# Exit on error
set -e

# Define root directory and output file
# Using a more robust way to find the root directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
OUTPUT_FILE="$ROOT_DIR/packages/config/src/generated-env.ts"

echo "Generating configuration from environment variables..."

# Start the file content
cat <<EOF > "$OUTPUT_FILE"
/*
 * THIS FILE IS GENERATED BY tools/generate-config.sh
 * DO NOT EDIT DIRECTLY.
 */

export const generatedEnv = {
EOF

# Function to append config if variable exists
# Usage: append_config "ENV_VAR_NAME" "configKey" "type"
append_config() {
  local env_var="$1"
  local config_key="$2"
  local type="$3" # string, boolean, number
  
  # Get the value of the environment variable
  local value="${!env_var}"
  
  if [ -n "$value" ]; then
    if [ "$type" == "string" ]; then
      echo "  $config_key: \"$value\"," >> "$OUTPUT_FILE"
    elif [ "$type" == "boolean" ]; then
      if [ "$value" == "true" ]; then
        echo "  $config_key: true," >> "$OUTPUT_FILE"
      else
        echo "  $config_key: false," >> "$OUTPUT_FILE"
      fi
    elif [ "$type" == "number" ]; then
      echo "  $config_key: $value," >> "$OUTPUT_FILE"
    fi
  fi
}

# Algorand Node URLs
append_config "MAINNET_ALGOD_URL" "mainnetAlgodUrl" "string"
append_config "TESTNET_ALGOD_URL" "testnetAlgodUrl" "string"
append_config "MAINNET_INDEXER_URL" "mainnetIndexerUrl" "string"
append_config "TESTNET_INDEXER_URL" "testnetIndexerUrl" "string"

# Backend URLs and API Keys
append_config "MAINNET_BACKEND_URL" "mainnetBackendUrl" "string"
append_config "TESTNET_BACKEND_URL" "testnetBackendUrl" "string"
append_config "BACKEND_API_KEY" "backendAPIKey" "string"
append_config "ALGOD_API_KEY" "algodApiKey" "string"
append_config "INDEXER_API_KEY" "indexerApiKey" "string"

# App Store ID
append_config "APP_STORE_APP_ID" "appStoreAppID" "string"

# Explorer URLs
append_config "MAINNET_EXPLORER_URL" "mainnetExplorerUrl" "string"
append_config "TESTNET_EXPLORER_URL" "testnetExplorerUrl" "string"

# Base URLs
append_config "DISCOVER_BASE_URL" "discoverBaseUrl" "string"
append_config "STAKING_BASE_URL" "stakingBaseUrl" "string"
append_config "ONRAMP_BASE_URL" "onrampBaseUrl" "string"
append_config "SUPPORT_BASE_URL" "supportBaseUrl" "string"
append_config "TOS_URL" "termsOfServiceUrl" "string"
append_config "PRIVACY_POLICY_URL" "privacyPolicyUrl" "string"
append_config "DEMO_DAPP_URL" "peraDemoDappUrl" "string"

# Feature Flags and Debugging
append_config "DEBUG_ENABLED" "debugEnabled" "boolean"
append_config "PROFILING_ENABLED" "profilingEnabled" "boolean"
append_config "POLLING_ENABLED" "pollingEnabled" "boolean"

# Close the object
echo "} as const;" >> "$OUTPUT_FILE"

echo "✓ Configuration generated at $OUTPUT_FILE"
echo "Values included: $(grep -c ":" "$OUTPUT_FILE")"
