#!/usr/bin/env node
/*
 Copyright 2022-2025 Pera Wallet, LDA
 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 limitations under the License
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.join(__dirname, '..');

// Parse command line arguments or environment variable
const environment = process.argv[2] || process.env.APP_ENV || 'development';

console.log(`Generating configuration for environment: ${environment}`);

const envFiles = [
    path.join(rootDir, 'fastlane', `.env.${environment}`),
    path.join(rootDir, 'packages', 'config', '.env'),
    path.join(rootDir, 'packages', 'config', '.env.example'),
];

const config = {};

// Simple .env parser
function parseEnv(filePath) {
    if (!fs.existsSync(filePath)) return {};
    const content = fs.readFileSync(filePath, 'utf8');
    const result = {};
    content.split('\n').forEach(line => {
        line = line.trim();
        if (line && !line.startsWith('#')) {
            const [key, ...valueParts] = line.split('=');
            const value = valueParts.join('=').trim();
            if (key) {
                // Remove quotes if present
                result[key.trim()] = value.replace(/^["']|["']$/g, '');
            }
        }
    });
    return result;
}

// 1. Load from .env files (earlier files in array have higher priority)
// Wait, actually later loads should override earlier ones if we want priority.
// Or we can reverse the array. Let's do it in order of increasing priority.
const prioritizedEnvFiles = envFiles.reverse();

prioritizedEnvFiles.forEach(file => {
    const fileConfig = parseEnv(file);
    Object.assign(config, fileConfig);
});

// 2. Override with process.env (highest priority)
Object.keys(process.env).forEach(key => {
    if (key.startsWith('PERA_')) {
        config[key] = process.env[key];
    }
});

// Map env vars to config keys
const mapping = {
    PERA_MAINNET_BACKEND_URL: 'mainnetBackendUrl',
    PERA_TESTNET_BACKEND_URL: 'testnetBackendUrl',
    PERA_MAINNET_ALGOD_URL: 'mainnetAlgodUrl',
    PERA_TESTNET_ALGOD_URL: 'testnetAlgodUrl',
    PERA_MAINNET_INDEXER_URL: 'mainnetIndexerUrl',
    PERA_TESTNET_INDEXER_URL: 'testnetIndexerUrl',
    PERA_BACKEND_API_KEY: 'backendAPIKey',
    PERA_ALGOD_API_KEY: 'algodApiKey',
    PERA_INDEXER_API_KEY: 'indexerApiKey',
    PERA_DEBUG_ENABLED: 'debugEnabled',
    PERA_PROFILING_ENABLED: 'profilingEnabled',
    PERA_POLLING_ENABLED: 'pollingEnabled',
};

const generatedConfig = {};
Object.entries(mapping).forEach(([envKey, configKey]) => {
    if (config[envKey] !== undefined && config[envKey] !== '') {
        let value = config[envKey];
        // Handle booleans
        if (value === 'true') value = true;
        if (value === 'false') value = false;
        generatedConfig[configKey] = value;
    }
});

const outputContent = `/*
 * THIS FILE IS GENERATED BY tools/generate-config.mjs
 * DO NOT EDIT DIRECTLY.
 */

export const generatedEnv = ${JSON.stringify(generatedConfig, null, 2)} as const;
`;

const outputPath = path.join(rootDir, 'packages', 'config', 'src', 'generated-env.ts');
fs.writeFileSync(outputPath, outputContent);

console.log(`✓ Configuration generated at ${outputPath}`);
