#!/bin/bash

# tools/generate-config.sh
# Generates a TypeScript configuration file from environment variables.
# This script is intended to be used in both local and CI environments.

# Exit on error
set -e

# Define root directory and output file
# Using a more robust way to find the root directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
OUTPUT_FILE="${OUTPUT_FILE:-$ROOT_DIR/packages/config/src/generated-env.ts}"
ENV_FILE="${ENV_FILE:-$ROOT_DIR/.env}"

# Load .env file if it exists
if [ -f "$ENV_FILE" ]; then
  echo "Loading environment variables from $ENV_FILE"
  export $(grep -v '^#' "$ENV_FILE" | xargs)
fi

# Load an optional overlay file (e.g. .env.localnet) AFTER .env so it wins.
if [ -n "${PERA_ENV_OVERLAY:-}" ] && [ -f "$PERA_ENV_OVERLAY" ]; then
  echo "Loading overlay environment variables from $PERA_ENV_OVERLAY"
  export $(grep -v '^#' "$PERA_ENV_OVERLAY" | xargs)
fi

echo "Generating configuration from environment variables..."

# Start the file content
cat <<EOF > "$OUTPUT_FILE"
/*
 * THIS FILE IS GENERATED BY tools/generate-config.sh
 * DO NOT EDIT DIRECTLY.
 */

export const generatedEnv = {
EOF

# Function to append config if variable exists
# Usage: append_config "ENV_VAR_NAME" "configKey" "type"
append_config() {
  local env_var="$1"
  local config_key="$2"
  local type="$3" # string, boolean, number
  
  # Get the value of the environment variable
  local value="${!env_var}"
  
  if [ -n "$value" ]; then
    if [ "$type" == "string" ]; then
      echo "  $config_key: \"$value\"," >> "$OUTPUT_FILE"
    elif [ "$type" == "boolean" ]; then
      if [ "$value" == "true" ]; then
        echo "  $config_key: true," >> "$OUTPUT_FILE"
      else
        echo "  $config_key: false," >> "$OUTPUT_FILE"
      fi
    elif [ "$type" == "number" ]; then
      echo "  $config_key: $value," >> "$OUTPUT_FILE"
    fi
  fi
}

# Algorand Node URLs
append_config "MAINNET_ALGOD_URL" "mainnetAlgodUrl" "string"
append_config "TESTNET_ALGOD_URL" "testnetAlgodUrl" "string"
append_config "MAINNET_INDEXER_URL" "mainnetIndexerUrl" "string"
append_config "TESTNET_INDEXER_URL" "testnetIndexerUrl" "string"
append_config "MAINNET_GENESIS_HASH" "mainnetGenesisHash" "string"
append_config "TESTNET_GENESIS_HASH" "testnetGenesisHash" "string"

# Backend URLs and API Keys
append_config "MAINNET_BACKEND_URL" "mainnetBackendUrl" "string"
append_config "TESTNET_BACKEND_URL" "testnetBackendUrl" "string"
append_config "BACKEND_API_KEY" "backendAPIKey" "string"
append_config "ALGOD_API_KEY" "algodApiKey" "string"
append_config "INDEXER_API_KEY" "indexerApiKey" "string"

# App Store ID (per-env: {PRODUCTION_,STAGING_}APP_STORE_APPLE_ID, aliased by setup-env-secrets.sh)
append_config "APP_STORE_APPLE_ID" "appStoreAppID" "string"
append_config "PLAY_INTEGRITY_CLOUD_PROJECT_NUMBER" "playIntegrityCloudProjectNumber" "string"

# Firebase Web SDK config (browser extension Remote Config)
append_config "FIREBASE_API_KEY" "firebaseApiKey" "string"
append_config "FIREBASE_AUTH_DOMAIN" "firebaseAuthDomain" "string"
append_config "FIREBASE_DATABASE_URL" "firebaseDatabaseUrl" "string"
append_config "FIREBASE_PROJECT_ID" "firebaseProjectId" "string"
append_config "FIREBASE_STORAGE_BUCKET" "firebaseStorageBucket" "string"
append_config "FIREBASE_MESSAGING_SENDER_ID" "firebaseMessagingSenderId" "string"
append_config "FIREBASE_APP_ID" "firebaseAppId" "string"
append_config "FIREBASE_MEASUREMENT_ID" "firebaseMeasurementId" "string"

# GA4 Measurement Protocol + Sentry (browser extension analytics/crash reporting)
append_config "GA_MEASUREMENT_API_SECRET" "gaMeasurementApiSecret" "string"
append_config "SENTRY_DSN" "sentryDsn" "string"

# Build channel (development | staging | production)
append_config "APP_ENV" "appEnvironment" "string"

# Full git release tag (e.g. v7.0.0-alpha.9) for the in-app QA version display.
# Set by Bitrise on tag builds; absent locally/off-tag.
append_config "BITRISE_GIT_TAG" "releaseTag" "string"

# Incrementing CI build number, mirroring mobile's native build version.
# Set by Bitrise; absent locally.
append_config "BITRISE_BUILD_NUMBER" "appBuildNumber" "string"

# Explorer URLs
append_config "MAINNET_EXPLORER_URL" "mainnetExplorerUrl" "string"
append_config "TESTNET_EXPLORER_URL" "testnetExplorerUrl" "string"

# Base URLs
append_config "SUPPORT_BASE_URL" "supportBaseUrl" "string"
append_config "TOS_URL" "termsOfServiceUrl" "string"
append_config "PRIVACY_POLICY_URL" "privacyPolicyUrl" "string"
append_config "DEMO_DAPP_URL" "peraDemoDappUrl" "string"

# Feature Flags and Debugging
append_config "DEBUG_ENABLED" "debugEnabled" "boolean"
append_config "PROFILING_ENABLED" "profilingEnabled" "boolean"
append_config "POLLING_ENABLED" "pollingEnabled" "boolean"
# e2e-only: disables FLAG_SECURE so Appium/BrowserStack can drive the app.
# Set ONLY in the e2e build job — never in store-submission builds.
append_config "DISABLE_SCREEN_CAPTURE_PREVENTION" "disableScreenCapturePrevention" "boolean"

append_config "MAINNET_BIDALI_API_KEY" "mainnetBidaliApiKey" "string"
append_config "TESTNET_BIDALI_API_KEY" "testnetBidaliApiKey" "string"
append_config "MAINNET_BIDALI_BASE_URL" "mainnetBidaliBaseUrl" "string"
append_config "TESTNET_BIDALI_BASE_URL" "testnetBidaliBaseUrl" "string"

# Baanx card integration. The x-client-key is a PUBLIC client identifier;
# inject the sandbox key via TESTNET_BAANX_CLIENT_KEY (bitrise secret / .env).
# The server-only x-secret-key MUST NEVER be added here.
append_config "MAINNET_BAANX_BASE_URL" "mainnetBaanxBaseUrl" "string"
append_config "TESTNET_BAANX_BASE_URL" "testnetBaanxBaseUrl" "string"
append_config "MAINNET_BAANX_CLIENT_KEY" "mainnetBaanxClientKey" "string"
append_config "TESTNET_BAANX_CLIENT_KEY" "testnetBaanxClientKey" "string"

# AppliedBlockchain (AB) escrow card service — card creation + delegated-LSig
# `/lsig` endpoint, AB-hosted on testnet until Baanx wraps them. The auth token
# is an AB-issued static secret sent as a RAW Authorization header; inject via
# the bitrise secret / .env. App ids and the USDC asset id feed the AutoDraw
# LogicSig TEAL template.
append_config "MAINNET_CARD_ESCROW_BASE_URL" "mainnetCardEscrowBaseUrl" "string"
append_config "TESTNET_CARD_ESCROW_BASE_URL" "testnetCardEscrowBaseUrl" "string"
append_config "MAINNET_CARD_ESCROW_AUTH_TOKEN" "mainnetCardEscrowAuthToken" "string"
append_config "TESTNET_CARD_ESCROW_AUTH_TOKEN" "testnetCardEscrowAuthToken" "string"
append_config "MAINNET_CARD_W3CARD_APP_ID" "mainnetCardW3CardAppId" "string"
append_config "TESTNET_CARD_W3CARD_APP_ID" "testnetCardW3CardAppId" "string"
append_config "MAINNET_CARD_KILLSWITCH_APP_ID" "mainnetCardKillswitchAppId" "string"
append_config "TESTNET_CARD_KILLSWITCH_APP_ID" "testnetCardKillswitchAppId" "string"
append_config "MAINNET_CARD_USDC_ASSET_ID" "mainnetCardUsdcAssetId" "string"
append_config "TESTNET_CARD_USDC_ASSET_ID" "testnetCardUsdcAssetId" "string"

# Default Network
if [ -n "$PERA_DEFAULT_NETWORK" ] && [ -z "$DEFAULT_NETWORK" ]; then
  DEFAULT_NETWORK="$PERA_DEFAULT_NETWORK"
fi
append_config "DEFAULT_NETWORK" "defaultNetwork" "string"

# Close the object
echo "} as const;" >> "$OUTPUT_FILE"

echo "✓ Configuration generated at $OUTPUT_FILE"
echo "Values included: $(grep -c ":" "$OUTPUT_FILE")"
