#!/usr/bin/env bash
set -uo pipefail

# tools/publish-github-release.sh <tag>
#
# Publishes a GitHub Release for a release tag. Notes are generated by GitHub
# from the range since the previous tag on the same channel, so a nightly lists
# one day of work and an rc lists the whole week. alpha and rc are marked
# prerelease; a bare vX.Y.Z becomes the latest release.
#
# Idempotent: an existing release is left untouched, so re-running is harmless
# and a hand-pushed tag that also trips the tag workflow can't double-publish.
#
# Env:
#   GH_TOKEN  required, needs contents: write
#   DRY_RUN   when "1": print the gh command that would run and exit without
#             creating anything (same convention as create-nightly-tag.sh)

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

TAG="${1:-}"
if [ -z "$TAG" ]; then
    echo "publish-github-release: no tag given — nothing to do"
    exit 0
fi

if ! git rev-parse -q --verify "refs/tags/${TAG}" >/dev/null 2>&1; then
    echo "::warning::${TAG} is not a tag in this checkout — skipping release"
    exit 0
fi

# The same shape Bitrise's release-builds trigger accepts. Without this a stray
# tag like `vfoo` would fall through to the stable branch below and be published
# as a full release.
if ! [[ "$TAG" =~ ^v[0-9]+\.[0-9]+\.[0-9]+(-(alpha|rc)\.[0-9]+)?$ ]]; then
    echo "::warning::${TAG} is not a release tag (vX.Y.Z[-alpha.N|-rc.N]) — skipping release"
    exit 0
fi

args=(--verify-tag --title "$TAG" --generate-notes)
case "$TAG" in
    *-alpha.* | *-rc.*)
        args+=(--prerelease)
        ;;
    *)
        # Claim "Latest" only when this really is the newest stable. Backfilling an
        # older release must not take the badge off a shipped one, and gh's own
        # default already picks sensibly when the flag is absent.
        # Exact shape, not "anything without -alpha/-rc": a stray tag would
        # otherwise count as a stable release and win this comparison.
        newest_stable=$(git tag --list 'v*' --sort=-v:refname |
            grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | head -1)
        if [ "$TAG" = "$newest_stable" ]; then
            args+=(--latest)
        else
            echo "not the newest stable (${newest_stable:-none}) — leaving the Latest badge alone"
        fi
        ;;
esac

PREV=$("${ROOT_DIR}/tools/previous-release-tag.sh" "$TAG")
if [ -n "$PREV" ]; then
    args+=(--notes-start-tag "$PREV")
    echo "notes range: ${PREV}..${TAG}"
else
    echo "no earlier tag on this channel — letting GitHub choose the notes range"
fi

if [ "${DRY_RUN:-}" = "1" ]; then
    echo "DRY_RUN=1 — would run: gh release create ${TAG} ${args[*]}"
    exit 0
fi

if gh release view "$TAG" >/dev/null 2>&1; then
    echo "release ${TAG} already exists — left as published"
    exit 0
fi

# A missing release note must not fail the job that just minted the tag.
if gh release create "$TAG" "${args[@]}"; then
    echo "published ${TAG}"
else
    echo "::warning::could not publish release ${TAG}"
fi
exit 0
