#!/usr/bin/env bash
set -uo pipefail

# tools/publish-github-release.sh <tag>
#
# Publishes a GitHub Release for a stable release tag (vX.Y.Z). Notes are
# generated by GitHub from the range since the previous stable tag, and the
# newest stable claims the "Latest" badge.
#
# Prereleases are deliberately not published: nightly (-alpha.N) and rc (-rc.N)
# tags exist to fire Bitrise's release builds, not to appear under Releases. The
# rule lives here rather than in the workflow so the `push: tags` trigger and the
# manual workflow_dispatch backfill cannot drift apart — every caller gets the
# same answer for the same tag.
#
# Idempotent: an existing release is left untouched, so re-running is harmless
# and a hand-pushed tag that also trips the tag workflow can't double-publish.
#
# Env:
#   GH_TOKEN  required, needs contents: write
#   DRY_RUN   when "1": print the gh command that would run and exit without
#             creating anything (same convention as create-nightly-tag.sh)

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

TAG="${1:-}"
if [ -z "$TAG" ]; then
    echo "publish-github-release: no tag given — nothing to do"
    exit 0
fi

if ! git rev-parse -q --verify "refs/tags/${TAG}" >/dev/null 2>&1; then
    echo "::warning::${TAG} is not a tag in this checkout — skipping release"
    exit 0
fi

# Expected, not an anomaly: these tags are minted on a schedule, so a warning
# here would just be recurring noise in otherwise-green runs.
if [[ "$TAG" =~ ^v[0-9]+\.[0-9]+\.[0-9]+-(alpha|rc)\.[0-9]+$ ]]; then
    echo "${TAG} is a prerelease tag — no GitHub release by design"
    exit 0
fi

# Exact stable shape. Without this a stray tag like `vfoo` would be published as
# a full release.
if ! [[ "$TAG" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
    echo "::warning::${TAG} is not a stable release tag (vX.Y.Z) — skipping release"
    exit 0
fi

args=(--verify-tag --title "$TAG" --generate-notes)

# Claim "Latest" only when this really is the newest stable. Backfilling an older
# release must not take the badge off a shipped one, and gh's own default already
# picks sensibly when the flag is absent.
# Exact shape, not "anything without -alpha/-rc": a stray tag would otherwise
# count as a stable release and win this comparison.
newest_stable=$(git tag --list 'v*' --sort=-v:refname |
    grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | head -1)
if [ "$TAG" = "$newest_stable" ]; then
    args+=(--latest)
else
    echo "not the newest stable (${newest_stable:-none}) — leaving the Latest badge alone"
fi

PREV=$("${ROOT_DIR}/tools/previous-release-tag.sh" "$TAG")
if [ -n "$PREV" ]; then
    args+=(--notes-start-tag "$PREV")
    echo "notes range: ${PREV}..${TAG}"
else
    echo "no earlier tag on this channel — letting GitHub choose the notes range"
fi

if [ "${DRY_RUN:-}" = "1" ]; then
    echo "DRY_RUN=1 — would run: gh release create ${TAG} ${args[*]}"
    exit 0
fi

if gh release view "$TAG" >/dev/null 2>&1; then
    echo "release ${TAG} already exists — left as published"
    exit 0
fi

# A missing release note must not fail the job that just minted the tag.
if gh release create "$TAG" "${args[@]}"; then
    echo "published ${TAG}"
else
    echo "::warning::could not publish release ${TAG}"
fi
exit 0
