/*
 Copyright 2022-2026 Pera Wallet, LDA
 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License
 */

/* eslint-disable @typescript-eslint/no-require-imports */
const { withAppBuildGradle } = require('expo/config-plugins');

/**
 * @type {import('expo/config-plugins').ConfigPlugin}
 *
 * Makes Android release builds emit FULL native debug symbols and upload them
 * to Firebase Crashlytics, so native (`.so`) crashes — Hermes, React Native
 * core, quick-crypto, MMKV, etc. — are symbolicated instead of showing raw
 * addresses. This is the Android counterpart to the iOS dSYM upload in
 * fastlane/Fastfile (`upload_symbols_to_crashlytics`).
 *
 * The symbols are consumed by Crashlytics / embedded in the AAB metadata for
 * Play Console; they are NOT delivered to devices, so this does not increase
 * the installed app size. app/build.gradle is regenerated by `expo prebuild`,
 * so this mod re-applies on every prebuild.
 *
 * NOTE: symbol UPLOAD is separate from native-crash CAPTURE. If native crashes
 * should also be recorded by Crashlytics on Android, verify the
 * `firebase-crashlytics-ndk` dependency is present (follow-up).
 */
const withAndroidNativeSymbolUpload = (config) => {
  return withAppBuildGradle(config, (config) => {
    if (config.modResults.language !== 'groovy') {
      throw new Error(
        '[withAndroidNativeSymbolUpload] app/build.gradle is not groovy; cannot patch native symbol config',
      );
    }
    config.modResults.contents = addNativeSymbolUpload(
      config.modResults.contents,
    );
    return config;
  });
};

function addNativeSymbolUpload(buildGradle) {
  let patched = buildGradle;

  // Idempotent: prebuild re-runs mods, and we must not inject the block twice.
  if (!patched.includes('debugSymbolLevel')) {
    const injected = [
      '            // Native debug symbols for release crash symbolication.',
      '            // Uploaded to Crashlytics / Play Console metadata, never',
      '            // shipped to devices.',
      "            ndk {\n                debugSymbolLevel 'FULL'\n            }",
      '            firebaseCrashlytics {\n                nativeSymbolUploadEnabled true\n            }',
      '',
    ]
      .map((line) => (line ? `${line}` : line))
      .join('\n');

    // Anchor inside `buildTypes { ... release { ` so only the release buildType is
    // touched, and inject immediately after the release block opens.
    patched = patched.replace(
      /(buildTypes\s*\{[\s\S]*?release\s*\{\n)/,
      (match) => `${match}${injected}\n`,
    );

    if (patched === buildGradle) {
      throw new Error(
        '[withAndroidNativeSymbolUpload] could not find the release buildType to patch',
      );
    }
  }

  // The injected `firebaseCrashlytics {}` DSL is evaluated while the `android {}`
  // block is configured, so `com.google.firebase.crashlytics` must be applied
  // BEFORE that block. @react-native-firebase/crashlytics appends the apply at
  // the END of app/build.gradle (too late), producing a "Could not find method
  // firebaseCrashlytics()" failure. Hoist it above `android {`. Idempotent.
  return hoistCrashlyticsApply(patched);
}

function hoistCrashlyticsApply(buildGradle) {
  const APPLY = "apply plugin: 'com.google.firebase.crashlytics'";
  // Remove every existing apply of the crashlytics plugin, wherever it sits,
  // along with any blank line it left behind (keeps the transform idempotent).
  // The trailing newline is optional (`\r?\n?`): Expo emits this apply as the
  // very last line of app/build.gradle with NO trailing newline, so requiring
  // one here would leave the original in place and duplicate the apply.
  const stripped = buildGradle.replace(
    /^[ \t]*apply plugin: ['"]com\.google\.firebase\.crashlytics['"].*\r?\n?(?:[ \t]*\r?\n)*/gm,
    '',
  );
  // Re-insert exactly one, immediately before the top-level `android {` block.
  const hoisted = stripped.replace(/^android\s*\{/m, `${APPLY}\n\nandroid {`);

  if (hoisted === stripped) {
    throw new Error(
      '[withAndroidNativeSymbolUpload] could not find `android {` to hoist the crashlytics apply',
    );
  }

  return hoisted;
}

module.exports = withAndroidNativeSymbolUpload;
module.exports.addNativeSymbolUpload = addNativeSymbolUpload;
