/*
 Copyright 2022-2026 Pera Wallet, LDA
 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License
 */

/* eslint-disable @typescript-eslint/no-require-imports */
const { withAndroidManifest } = require('expo/config-plugins');

/**
 * @type {import('expo/config-plugins').ConfigPlugin}
 *
 * Enables GWP-ASan in "always" mode on the Android `<application>`. GWP-ASan is
 * a low-overhead sampling allocator (Android 11+) that detects native heap
 * memory-safety bugs — use-after-free, buffer/heap overflow — the class behind
 * hard-to-debug NDK `SIGABRT`/`SIGSEGV` crashes that can carry security impact.
 * When it trips, Crashlytics receives allocation/deallocation stacks instead of
 * a bare abort, making native crashes actionable. Pairs with the native symbol
 * upload (`withAndroidNativeSymbolUpload`), which makes the frames readable.
 *
 * The attribute is ignored below API 30, so it's safe at our minSdk (29).
 * app/AndroidManifest.xml is regenerated by `expo prebuild`, so this re-applies.
 */
const GWP_ASAN_ATTR = 'android:gwpAsanMode';
const GWP_ASAN_MODE = 'always';

const withAndroidGwpAsan = (config) =>
  withAndroidManifest(config, (config) => {
    config.modResults = setGwpAsanMode(config.modResults);
    return config;
  });

/**
 * Set `gwpAsanMode="always"` on the `<application>` tag. Pure and idempotent so
 * repeated prebuilds don't duplicate it and it can be unit-tested directly.
 *
 * @param {{ manifest: { application?: Array<{ $?: Record<string, string> }> } }} androidManifest
 * @returns {typeof androidManifest}
 */
function setGwpAsanMode(androidManifest) {
  const application = androidManifest?.manifest?.application?.[0];
  if (!application) {
    throw new Error(
      '[withAndroidGwpAsan] <application> not found in AndroidManifest',
    );
  }
  application.$ = application.$ ?? {};
  application.$[GWP_ASAN_ATTR] = GWP_ASAN_MODE;
  return androidManifest;
}

module.exports = Object.assign(withAndroidGwpAsan, { setGwpAsanMode });
