/*
 Copyright 2022-2026 Pera Wallet, LDA
 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License
 */

/* eslint-disable @typescript-eslint/no-require-imports */
const { withGradleProperties } = require('expo/config-plugins');

/**
 * @type {import('expo/config-plugins').ConfigPlugin}
 *
 * Raises the Gradle daemon + Kotlin daemon JVM heap for Android builds.
 *
 * The Expo/RN template default (`-Xmx2048m`) OOMs this monorepo's Android
 * build: `:expo:compileDebugKotlin` fails with "Java heap space" and
 * `:app:mergeExtDexDebug` dies with a detail-less dex-merge error (also OOM),
 * especially with `org.gradle.parallel=true` where dex-merge and Kotlin
 * compile run concurrently in the same daemon.
 *
 * `android/` is regenerated by `expo prebuild`, so a manual `gradle.properties`
 * edit is wiped by `expo prebuild --clean`. Setting it here makes the heap
 * durable. Runs after `expo-build-properties`, so these values win.
 */
const GRADLE_JVM_ARGS = '-Xmx6144m -XX:MaxMetaspaceSize=1024m';
const KOTLIN_DAEMON_JVM_ARGS = '-Xmx3072m';

const withAndroidGradleHeap = (config) => {
  return withGradleProperties(config, (config) => {
    config.modResults = setProperty(
      config.modResults,
      'org.gradle.jvmargs',
      GRADLE_JVM_ARGS,
    );
    config.modResults = setProperty(
      config.modResults,
      'kotlin.daemon.jvmargs',
      KOTLIN_DAEMON_JVM_ARGS,
    );

    return config;
  });
};

/**
 * Set a gradle.properties key: overwrite it in place if present, otherwise
 * append it. Idempotent — repeated prebuilds never duplicate the key.
 */
function setProperty(items, key, value) {
  const existing = items.find(
    (item) => item.type === 'property' && item.key === key,
  );

  if (existing) {
    existing.value = value;
    return items;
  }

  return [...items, { type: 'property', key, value }];
}

module.exports = Object.assign(withAndroidGradleHeap, { setProperty });
