/*
 Copyright 2022-2025 Pera Wallet, LDA
 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License
 */

/* eslint-disable @typescript-eslint/no-require-imports */
const { withAppBuildGradle } = require('expo/config-plugins');

/**
 * @type {import('expo/config-plugins').ConfigPlugin}
 *
 * Makes Android release builds emit FULL native debug symbols and upload them
 * to Firebase Crashlytics, so native (`.so`) crashes — Hermes, React Native
 * core, quick-crypto, MMKV, etc. — are symbolicated instead of showing raw
 * addresses. This is the Android counterpart to the iOS dSYM upload in
 * fastlane/Fastfile (`upload_symbols_to_crashlytics`).
 *
 * The symbols are consumed by Crashlytics / embedded in the AAB metadata for
 * Play Console; they are NOT delivered to devices, so this does not increase
 * the installed app size. app/build.gradle is regenerated by `expo prebuild`,
 * so this mod re-applies on every prebuild.
 *
 * NOTE: symbol UPLOAD is separate from native-crash CAPTURE. If native crashes
 * should also be recorded by Crashlytics on Android, verify the
 * `firebase-crashlytics-ndk` dependency is present (follow-up).
 */
const withAndroidNativeSymbolUpload = (config) => {
  return withAppBuildGradle(config, (config) => {
    if (config.modResults.language !== 'groovy') {
      throw new Error(
        '[withAndroidNativeSymbolUpload] app/build.gradle is not groovy; cannot patch native symbol config',
      );
    }
    config.modResults.contents = addNativeSymbolUpload(
      config.modResults.contents,
    );
    return config;
  });
};

function addNativeSymbolUpload(buildGradle) {
  // Idempotent: prebuild re-runs mods, and we must not inject twice.
  if (buildGradle.includes('debugSymbolLevel')) {
    return buildGradle;
  }

  const injected = [
    '            // Native debug symbols for release crash symbolication (see',
    '            // docs/SECURITY_OBFUSCATION_AUDIT.md). Uploaded to Crashlytics /',
    '            // Play Console metadata, not shipped to devices.',
    "            ndk {\n                debugSymbolLevel 'FULL'\n            }",
    '            firebaseCrashlytics {\n                nativeSymbolUploadEnabled true\n            }',
    '',
  ]
    .map((line) => (line ? `${line}` : line))
    .join('\n');

  // Anchor inside `buildTypes { ... release { ` so only the release buildType is
  // touched, and inject immediately after the release block opens.
  const patched = buildGradle.replace(
    /(buildTypes\s*\{[\s\S]*?release\s*\{\n)/,
    (match) => `${match}${injected}\n`,
  );

  if (patched === buildGradle) {
    throw new Error(
      '[withAndroidNativeSymbolUpload] could not find the release buildType to patch',
    );
  }

  return patched;
}

module.exports = withAndroidNativeSymbolUpload;
module.exports.addNativeSymbolUpload = addNativeSymbolUpload;
