/*
 Copyright 2022-2026 Pera Wallet, LDA
 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License
 */

/* eslint-disable @typescript-eslint/no-require-imports */
const { withMainActivity } = require('expo/config-plugins');

/**
 * @type {import('expo/config-plugins').ConfigPlugin}
 *
 * Guards a React Native crash: `ReactActivityDelegate.onUserLeaveHint()` runs
 * `Objects.requireNonNull(mReactDelegate).onUserLeaveHint()` and throws an NPE
 * when the user leaves the app (Home / Recents) before the React host is ready
 * or after it has been torn down. We don't use picture-in-picture, so overriding
 * onUserLeaveHint in MainActivity to swallow that race prevents the crash
 * (Crashlytics: NPE at ReactActivityDelegate.onUserLeaveHint). MainActivity is
 * regenerated by `expo prebuild`, so this re-applies each run.
 */
const OVERRIDE = [
  '  override fun onUserLeaveHint() {',
  '    // RN ReactActivityDelegate.onUserLeaveHint() does',
  '    // Objects.requireNonNull(mReactDelegate) and NPEs when the user leaves',
  '    // the app before the React host is ready / after teardown. We do not use',
  '    // picture-in-picture, so swallow that race instead of crashing.',
  '    try {',
  '      super.onUserLeaveHint()',
  '    } catch (e: NullPointerException) {',
  '      // no-op: React host not in a state to handle onUserLeaveHint',
  '    }',
  '  }',
].join('\n');

const withAndroidUserLeaveHintFix = (config) =>
  withMainActivity(config, (config) => {
    if (config.modResults.language !== 'kt') {
      throw new Error(
        '[withAndroidUserLeaveHintFix] MainActivity is not Kotlin; cannot patch',
      );
    }
    config.modResults.contents = addUserLeaveHintOverride(
      config.modResults.contents,
    );
    return config;
  });

/**
 * Inject the onUserLeaveHint override just before the MainActivity class's
 * closing brace (the final `}` of the file). Idempotent so repeated prebuilds
 * don't add it twice.
 */
function addUserLeaveHintOverride(mainActivity) {
  if (mainActivity.includes('onUserLeaveHint')) {
    return mainActivity;
  }

  const patched = mainActivity.replace(/\n\}\s*$/, `\n\n${OVERRIDE}\n}\n`);

  if (patched === mainActivity) {
    throw new Error(
      '[withAndroidUserLeaveHintFix] could not find the MainActivity class close to patch',
    );
  }

  return patched;
}

module.exports = Object.assign(withAndroidUserLeaveHintFix, {
  addUserLeaveHintOverride,
});
