/*
 Copyright 2022-2026 Pera Wallet, LDA
 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License
 */

/* eslint-disable @typescript-eslint/no-require-imports */
const {
  withAppBuildGradle,
  withGradleProperties,
} = require('expo/config-plugins');
const { setProperty } = require('./withAndroidGradleHeap');

/**
 * @type {import('expo/config-plugins').ConfigPlugin}
 *
 * Turns on the two R8 settings Play Console reports as missing ("Optimization
 * isn't enabled", "Optimized resource shrinking isn't enabled"). Minification
 * and resource shrinking are already on via `expo-build-properties`; these are
 * a separate axis, and neither is reachable through that plugin's options.
 *
 * 1. The RN template picks `proguard-android.txt`, which sets `-dontoptimize`.
 *    R8 therefore only shrinks and obfuscates — the whole optimization pass
 *    (inlining, class merging, dead-branch elimination) is skipped.
 *    `proguard-android-optimize.txt` is the same file without that line.
 *
 * 2. `preciseShrinking` lets the resource shrinker actually delete unused
 *    resources instead of replacing them with stub entries.
 *
 * Both raise the chance of a reflection-only path being stripped, so a release
 * smoke test belongs with this change — add any missing `-keep` rules from R8's
 * `missing_rules.txt` rather than pre-emptively over-keeping.
 *
 * `android/` is regenerated by `expo prebuild`, so both edits live here rather
 * than in the generated files.
 */
const DEFAULT_PROGUARD_FILE = 'proguard-android.txt';
const OPTIMIZED_PROGUARD_FILE = 'proguard-android-optimize.txt';
const PRECISE_SHRINKING_KEY =
  'android.enableNewResourceShrinker.preciseShrinking';

const withAndroidR8Optimization = (config) => {
  const withProguardFile = withAppBuildGradle(config, (config) => {
    if (config.modResults.language !== 'groovy') {
      throw new Error(
        '[withAndroidR8Optimization] app/build.gradle is not groovy; cannot patch proguardFiles',
      );
    }
    config.modResults.contents = useOptimizedProguardFile(
      config.modResults.contents,
    );
    return config;
  });

  return withGradleProperties(withProguardFile, (config) => {
    config.modResults = setProperty(
      config.modResults,
      PRECISE_SHRINKING_KEY,
      'true',
    );
    return config;
  });
};

function useOptimizedProguardFile(buildGradle) {
  // Idempotent: prebuild re-runs mods, and the second pass must be a no-op.
  if (buildGradle.includes(OPTIMIZED_PROGUARD_FILE)) {
    return buildGradle;
  }

  // Scoped to the getDefaultProguardFile() argument — a bare filename replace
  // would also rewrite a mention in a comment or a keep rule.
  const patched = buildGradle.replace(
    new RegExp(
      `(getDefaultProguardFile\\(\\s*["'])${DEFAULT_PROGUARD_FILE}(["']\\s*\\))`,
    ),
    `$1${OPTIMIZED_PROGUARD_FILE}$2`,
  );

  if (patched === buildGradle) {
    throw new Error(
      '[withAndroidR8Optimization] could not find getDefaultProguardFile("proguard-android.txt") to patch',
    );
  }

  return patched;
}

module.exports = withAndroidR8Optimization;
module.exports.useOptimizedProguardFile = useOptimizedProguardFile;
module.exports.PRECISE_SHRINKING_KEY = PRECISE_SHRINKING_KEY;
