/*
 Copyright 2022-2025 Pera Wallet, LDA
 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License
 */

/* eslint-disable @typescript-eslint/no-require-imports */
const { withAppBuildGradle } = require('expo/config-plugins');

/**
 * @type {import('expo/config-plugins').ConfigPlugin}
 *
 * Restricts Android *debug* builds to a single ABI (arm64-v8a), matching the
 * native Pera Android app (`app/build.gradle.kts`: debug → arm64-v8a only,
 * "faster builds"). Release is left untouched, so it keeps every ABI driven by
 * `reactNativeArchitectures` in gradle.properties (armeabi-v7a, x86, x86_64,
 * arm64-v8a) — device + emulator coverage for shipped builds is unchanged.
 *
 * Debug builds only ever run on the developer's own machine, so compiling all
 * four ABIs' native libraries (Hermes, Fabric, quick-crypto, nitro, reanimated,
 * …) is wasted work; a single ABI roughly quarters the native build for local
 * iteration. arm64-v8a covers real devices and Apple-silicon emulators (the
 * same choice native makes); developers on an x86_64 emulator can override
 * `reactNativeArchitectures` locally.
 *
 * app/build.gradle is regenerated by `expo prebuild`, so this re-applies each run.
 */
const DEBUG_ABI = 'arm64-v8a';

const withAndroidAbiFilters = (config) => {
  return withAppBuildGradle(config, (config) => {
    if (config.modResults.language !== 'groovy') {
      throw new Error(
        '[withAndroidAbiFilters] app/build.gradle is not groovy; cannot patch abiFilters',
      );
    }
    config.modResults.contents = addDebugAbiFilter(config.modResults.contents);
    return config;
  });
};

function addDebugAbiFilter(buildGradle) {
  const block = `            ndk {\n                abiFilters '${DEBUG_ABI}'\n            }`;

  // Idempotent: prebuild re-runs mods, and we must not inject the block twice.
  // Anchored to our exact injected block rather than a bare 'abiFilters'
  // substring, so an unrelated abiFilters usage elsewhere (a `splits { abi }`
  // block, a release-side ndk filter, …) can't cause a silent no-op that
  // leaves debug unscoped.
  if (buildGradle.includes(block)) {
    return buildGradle;
  }

  // Anchor inside `buildTypes { ... debug { ` — `debug` precedes `release` in
  // the RN template, and the lazy match starts at `buildTypes` so it skips the
  // earlier `signingConfigs { debug { ... } }`, which also opens a `debug {`.
  const patched = buildGradle.replace(
    /(buildTypes\s*\{[\s\S]*?\bdebug\s*\{\n)/,
    (match) => `${match}${block}\n`,
  );

  if (patched === buildGradle) {
    throw new Error(
      '[withAndroidAbiFilters] could not find the debug buildType to patch',
    );
  }

  return patched;
}

module.exports = withAndroidAbiFilters;
module.exports.addDebugAbiFilter = addDebugAbiFilter;
