/*
 Copyright 2022-2025 Pera Wallet, LDA
 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License
 */

/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ApplicationParams } from "./ApplicationParams.ts";

/**
 * @description Application index and its parameters
*/
export type Application = {
    /**
     * @description Round when this application was created.
     * @type integer | undefined
    */
    "created-at-round"?: number;
    /**
     * @description Whether or not this application is currently deleted.
     * @type boolean | undefined
    */
    deleted?: boolean;
    /**
     * @description Round when this application was deleted.
     * @type integer | undefined
    */
    "deleted-at-round"?: number;
    /**
     * @description application index.
     * @type integer
    */
    id: number;
    /**
     * @description Stores the global information associated with an application.
     * @type object
    */
    params: ApplicationParams;
};