/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod";

export const quoteUpdateSerializerResponseSchema = z.object({
    "id": z.number().int().optional(),
"exception_text": z.string().describe("Exception text that occurred when a user tried to sign the transactions or send them to the blockchain.").nullable().nullish()
    })

export type QuoteUpdateSerializerResponseSchema = z.infer<typeof quoteUpdateSerializerResponseSchema>