/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { meldQuoteSchema } from "../meldQuoteSchema.ts";
import { z } from "zod";

export const meldQuotesSerializerResponseSchema = z.object({
    "results": z.array(z.lazy(() => meldQuoteSchema)).optional()
    })

export type MeldQuotesSerializerResponseSchema = z.infer<typeof meldQuotesSerializerResponseSchema>