/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod";

export const calculatePeraFeeSerializerResponseSchema = z.object({
    "pera_fee_amount": z.string().optional()
    })

export type CalculatePeraFeeSerializerResponseSchema = z.infer<typeof calculatePeraFeeSerializerResponseSchema>